### ISSUE TITLE
 [BOUNTY] Anonymous funding for Developers

### ISSUE THREAD

**Issue by ghost** [CellularPrivacy/Android-IMSI-Catcher-Detector#1]
Hello,
New users need 10 posts to post in this thread:
http://forum.xda-developers.com/showthread.php?p=46957078

Would be awesome if you could pledge somewhere else (e.g. bitcoinstarter.com, ...)

My part:
EUR 50 in BTC as soon as their is a working (beta) app that can detect Silent SMS

Thanks!

**Comment by SecUpwN** [comment]
Just an update for @WebDesZ, @dalb8 and @domenkozar: We're now using Bountysource, which supports proper splitting. Press this button to donate [![Bountysource](https://www.bountysource.com/badge/team?team_id=40338&style=bounties_received)](https://www.bountysource.com/teams/android-imsi-catcher-detector) and see this [FAQ](https://github.com/bountysource/frontend/wiki/Frequently-Asked-Questions)!
