### ISSUE TITLE
Getting Neighboring Cells info

### ISSUE THREAD

**Issue by E3V3A** [CellularPrivacy/Android-IMSI-Catcher-Detector#100]
There is some issue with some phones in using getNeighboringCells() and getting info. This is apparently especially true for Samsung phones as user @rtreffer states:
 
>Sorry for the noise, it is used by Android-IMSI-Catcher-Detector, at least for the Neighboring Cells fragment. This won't work as implemented though, as the call to getNeighboringCells may return an empty result (although it works well on my Nexus 4 after some time). I've created a pull request that calls the getNeighboringCells more aggressively. Note that Samsung devices are known to ignore the call. The pull request makes it possible to see neighboring cells directly after bootup (after a short lag).

**Comment by E3V3A** [comment]
A well written comment about PSC from [StackOverflow](http://stackoverflow.com/questions/9701777/cellid-and-lac-psc-for-3g-neighboring-cells-in-android):

>In UMTS, the PSC is a kind of local cell identifier. It is "locally" unique in that all neighboring cell, as well as all neighbors of these cells, are guaranteed to have a different PSC than the current cell. It also means that you will not ever encounter two neighboring cells with the same PSC. However, there may well be cells with the same PSC located in different parts of the country.
> 
>The NeighboringCellInfo for a UMTS cell will only have the PSC set while all other fields (MCC, MNC, LAC, CID) will be invalid. The only way to find out these parameters would be to store all fields (MCC, MNC, LAC, CID as well as PSC) for every cell you encounter, then upon getting an "unknown" PSC look it up in the stored data. (You would need to filter for neighbors of the serving cell, as the PSC is only a locally unique ID, not a globally unique one).
> 
> As an alternative, the PSC of a cell along with the MCC/MNC/LAC/CID tuple of one of its neighbors is also a globally unique ID that you could use. Be aware, however, that each cell would have multiple such identifiers (one for each neighbor).

This complicates the collection of NC data when on UMTS networks... It may also explain # 208.

**Comment by Reegan01** [comment]
Can I able to get the name of Neighbouring cells(available networks) such as idea,airtel,aircel ? I can able to get MCC, MNC, LAC, CID but How to get the name of the neighbouring cell names.

**Comment by SecUpwN** [comment]
Is anyone currently working on this one? In `v0.1.27-alpha` the neighboring cells list is empty.

**Comment by E3V3A** [comment]
Yes, this should be looked into again. Since most people think NC list is not working when in fact it is, only that all fields apart PSC are empty or the decimal equivalent to `0xFFF FFFF`, since they're redundant. (At least this seem to be the common scenario on most Samsucks.)

**Comment by E3V3A** [comment]
We need to look at what neighboring cells returns, if AOS API is ok like above we can parse it directly, if not we can parse the radio logcat as I suggested [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/208#issuecomment-70379457).

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)

**Comment by SecUpwN** [comment]
Tested with Buildozer Build `B-528` (Git SHA-Hash `78400ae`) again and this seems fixed.
