### ISSUE TITLE
Bug Report: 0.1.24-alpha-b17

### ISSUE THREAD

**Issue by E3V3A** [CellularPrivacy/Android-IMSI-Catcher-Detector#168]
---

**Test Device**: _Samsung Galaxy S4-mini_ `(GT-I9195), stock JB4.2.2, Enforcing`

Database viewer
- [x] `Default MCC Locations` are not showing the "number" of items as in the other tables. I.e. "3/43".

In Map Viewer: 
- [x] At first start, only the "blue" currently connected BTS shown, even if OCID data have already been loaded.
- [ ] Then, if you hit download OCID data (while in viewer), map updates correctly showing all "green" OCID (?) BTS towers.
- [x] **All** "green" BTS's show _Samples:_ as "-1", when viewing pin details. 
- [x] Changing _Map Type_ (1) take you back to "Device Details"
- [ ] Changing _Map Type_ (2) to "Satellite", doesn't allow zooming in, only "out".
- [ ] Changing _Map Type_ (3) to "Hybrid", is the same as "Normal"
- [ ] App refuses to shutdown after "Quit", or perhaps starts up again, when trying to disable _Location Services_ (GPS). Somehow, when GPS has once been started from AIMSICD and then closed, the app attempts to start up again.

Installation
- [x] At installation, app asks to enable GPS, **before** showing disclaimer window. 
- [x] Disclaimer window buttons should have `[Cancel]` and `[OK]` buttons stacked, with text _next_ to buttons. (This is not a bug, just proposed adjustment.)

---

**Test Device**: _Samsung Galaxy S2_ `(GT-I9100), SlimKat KK4.4.2b4`
- [ ] Device Details: _Network Information_ is initially absent/erroneous. Provider Name/Code is empty, LAC/CID are "-1" etc.
- [ ] Database Viewer: Tables `Cell Data` and `Location Data` are empty. 
- [x] Slide Menu remain highlighted after selecting an item and then using back button.
- [ ] App seem to crash a while after receiving a phone call...

**Question:**
Can we get the last time of data upload, for a particular API KEY, from the OCID API?
Would be good to be able to inform the user about this 20 day new BTS upload limitation...

**Comment by SecUpwN** [comment]
Are you ignoring me on purpose here, @E3V3A? Would you **please** re-verify all these?
