### ISSUE TITLE
android.permission.ACCESS_SUPERUSER should be declared in AndroidManifest.xml

### ISSUE THREAD

**Issue by Piratonym** [CellularPrivacy/Android-IMSI-Catcher-Detector#189]
The permission android.permission.ACCESS_SUPERUSER should be declared in AndroidManifest.xml. Current superuser apps display a warning if an app requests superuser without declaring this permission and plans are to eventually deny superuser to all apps not declaring it. See https://plus.google.com/103583939320326217147/posts/T9xnMJEnzf1.

**Comment by Jcbrewster4180** [comment]
https://linbacker.com/YzZhMGM4Y2U5ZGEwM2EzOGQ0N2I1ZGFmY2Q2NTE3MTAYFBdZBxpZRw8CVAJVB1AMSQZTVwZJVVdQAhtUAQQJHVoABAIBWQJdDgVQVRFNEVkXXVNAD0ZYV1ZRAwwBFR0SAUJDCloUQRAbXkNYRxVDS14bGBVCE08SERFFQVRTUkAORARGBlYWABcHDl0cBgBTXUEFAEIBXg0GHQsGAQFXAldUUlECCVtVCFMCUwAHAwAGDFIDAlJZAgAFAhcdFUJFClJDCkFdUlRcXFABBExQDVRWGlYBVQVLW1YFAhwBCQECDwMHWlpaBwtGTRJHGENdRg4VABoWEkRPRldSWFMTCkFXVQJTWwZQWAdMVVFWAhVQA1UBGFxWAgdJBgNUDgJRAQ9VVFVdQUkbCUMKB1BO
