### ISSUE TITLE
OpenCellID versus OpenSignal

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#225]
[![OpenCellID](http://www.linux-magazin.de/var/linux_magazin/storage/images/media/linux-magazin/images/opencellid3/1002419-1-ger-DE/opencellid_opengraph_h.png)](http://opencellid.org/)  **versus** [![OpenSignal](https://lh6.ggpht.com/5Vlpsx8ZjkfLeLHpiMI79vx7bjU0ca3plMMHLHH0FDTVZisOFFP1RAZCpCe6MWtN9w=w300)](http://opensignal.com/)

**NOTE:** This Issue is not only meant for me, but also as a reference for other people asking this.

In the current version of our App, we make use of [OpenCellID](http://opencellid.org/). During the time when we implemented the automatic fetching of the API key, I had this strange coincidence where a girl walked up in front of me and showed me the really cool looking, polished [OpenSignal App](https://play.google.com/store/apps/details?id=com.staircase3.opensignal). And ever since then, I asked myself:
1. Why exactly are we using OpenCellID and not anything else?
2. What are the main differences between OpenCellID and OpenSignal?
3. Are we going to stick to OpenCellID even though [Mozilla Location Service](https://location.services.mozilla.com/) comes around the corner?

@E3V3A, I am not trying to bust on anything we're using right now, I just want everyone to know the reasoning we're using OpenCellID and not any other (possibly better) service out there. Thank you.

**Comment by katpatuka** [comment]
I do not really want to reopen this threat but just want to add another "Versus": cellmapper.net. ;)

**Comment by E3V3A** [comment]
@katpatuka  Hi! Thanks for trying to provide alternative solutions. 

Unfortunately [CellMapper](http://www.cellmapper.net/) is light years from production ready, at least that's the first impression I get when looking at the lack of documentation, lack of API, lack of info regarding their database contents and size and where and how they collect their info. In addition I see nothing about their copyrights and openness... [Here](https://en.wikipedia.org/wiki/Cell_ID)'s one list... Not showing many other services, like SkyHook etc.
