### ISSUE TITLE
Twitter Option - Not An Issue: Suggestion

### ISSUE THREAD

**Issue by avishekcode** [CellularPrivacy/Android-IMSI-Catcher-Detector#268]
I would love if someone Adds a small piece of code to it...
Every time someone gets attacked, it will put a anonymous Tweet on Twitter with Location Info and type of Attack...
Then we can see the statistics in a broad scale...
That will be awesome! :-)
##

**Comment by avishekcode** [comment]
@SecUpwN Good points, but remember, none of this will matter if no one finds this solution. With the Twitter integration not only it will add a Social Networking functionality, it will also go viral very fast... It will be a huge marketing boost to it... The negative points you mentioned are valid, but every thing has negative side to it.... But that is not stopping Facebook being a billion Dollar company, is it? That's way worse than any of these any day! LOL

**Comment by SecUpwN** [comment]
> With the Twitter integration not only it will add a Social Networking functionality, it will also go viral very fast... It will be a huge marketing boost to it.. Oh, and it can always upload the Twieet later..

Ok, I have to admit that such an option would indeed be one of uniqueness and we should carefully consider this one. How about if you add a proper pull request for this and we have a look, @avishekcode?

**Comment by avishekcode** [comment]
@SecUpwN I am seriously considering that... Thank you for appreciating the idea... I will definitely look into the codes soon, and consider getting into it more actively... I just did not want to sit back with the idea, which came to my mind immediately after noticing your amazing solution for the first time, like an hour back... Ultimately, it doesn't matter who makes it... It's just that, I think the society needs it...

**Comment by SecUpwN** [comment]
>...which came to my mind immediately after noticing your amazing solution for the first time...

Thank you for your warm words, I truly appreciate that. We are the people and we stand strong. We are not helpless and we will fight back! Spread the word about our project using the [Media Material](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Media-Material), please.

**Comment by E3V3A** [comment]
Only that twitter has a subsidiary of CIA as partial ownership... But I think we need to complete the event log output before, to ensure there's anything to twitter. Also, how do you intend to include that twitter account data?  We've been playing with a future idea, of submitting and sharing detections via a P2P network. 

So since we know that twitter is one of the first things a government gone-rougue is monitoring, I'm not a big fan of including this as a "feature" of this app. But if it's a matter of a small piece of code with opt-out as default, then maybe it's OK.

**Comment by andr3jx** [comment]
I advice not to access Twitter directly! A better solution is to setup a server (in a privacy-friendly country) which will publish the tweets. We plan to setup a server for BTS location requests and could add this feature.

**Comment by E3V3A** [comment]
That would be it.

**Comment by SecUpwN** [comment]
It makes less sense to add this suggestion any time soon until we can't be absolutely damn sure that our app is working the way we're intending to and that we're not going to scare Twitter users with false data. Nevertheless, I'll be re-opening this for further discussion. May I also suggest the server sending the tweets to publish those via our official Twitter account located at https://www.twitter.com/AIMSICD?
