### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by larsgrefer** [CellularPrivacy/Android-IMSI-Catcher-Detector#653]
@SecUpwN Do you have the icons as vector files?
##

**Comment by SecUpwN** [comment]
@larsgrefer, yes I do, they're on my computer across town. What would you like to do?

**Comment by larsgrefer** [comment]
add them as drawables to the app

**Comment by agilob** [comment]
Yes, @SecUpwN please add them to the repo.

**Comment by SecUpwN** [comment]
>add them as drawables to the app

I will be home later today and will add the link here later on. Hope @larsgrefer is able to use that file.

**Comment by larsgrefer** [comment]
@SecUpwN There is no need to zip them

SVG's are text files, so git can handle them pretty well

**Comment by SecUpwN** [comment]
>SVG's are text files, so git can handle them pretty well

I know, I thought you wanted to add them yourself. The Icons in our app are currently PNGs and had been shrinked before. Am I right assuming that I shall replace all PNG files with the SVG version of the Icon?

**Comment by larsgrefer** [comment]
I'm going to create new vector assets in `app/res/drawable` based on the svg's and then remove the png's in `app/res/drawable-*dpi`

**Comment by SecUpwN** [comment]
@larsgrefer, I see that you know what you're doing. I'll be sending the ZIP file to you, I don't want to mess up the code just because I don't have the right plan on how to add the SVG Icons. Stay tuned.

**Comment by agilob** [comment]
What else are you hiding there @SecUpwN ?

**Comment by SecUpwN** [comment]
@agilob, what do you mean by "hiding"? On my computer? A lot! :smile:

**Comment by larsgrefer** [comment]
@SecUpwN However you like :D

**Comment by agilob** [comment]
I meant files that could be useful, like those svgs.

**Comment by TPS** [comment]
I suppose this is somewhat interrelated to #512?

**Comment by SecUpwN** [comment]
>I meant files that could be useful, like those svgs.

Files that can be useful for this project reside in our [Research](https://spideroak.com/browse/share/AIMSICD/GitHub). Note: I am still tinkering with the thought of moving away from `SpiderOak` and towards [OwnCloud](https://owncloud.org/).

@larsgrefer, all images had been compressed with #378. What is the advantage of using SVGs now?

**Comment by larsgrefer** [comment]
On API > 21 the app will be smaller and we prevent redundancy in our sources
Am 04.12.2015 6:10 nachm. schrieb "Security: Pwned." <notifications@github.com>:
I meant files that could be useful, like those svgs.


Files that can be useful for this project reside in our Research. Note: I am still tinkering with the thought of moving away from SpiderOak and towards OwnCloud.

@larsgrefer, all images had been compressed with #378. What is the advantage of using SVGs now?

**Comment by SecUpwN** [comment]
>On API > 21 the app will be smaller and we prevent redundancy in our sources

Sounds great! @larsgrefer, did you have a look at the file sent to you several weeks ago? Important thing to note: When adding our Icons as SVGs, I would like to fully *remove* all metadata from these files before adding them, sadly [MAT](https://github.com/jvoisin/MAT) does not yet support cleaning SVGs. So how can we do this?

**Comment by TPS** [comment]
>When adding our Icons as SVGs, I would like to fully _remove_ all metadata from these files before adding them, sadly [MAT](https://github.com/jvoisin/MAT) does not yet support cleaning SVGs. So how can we do this?

@SecUpwN @larsgrefer https://github.com/JayXon/Leanify will do it, as well as optimize APK & all other contents, _after_ which you can sign the APK, however you choose.

**Comment by SecUpwN** [comment]
Pushing this Issue. @larsgrefer, will it be enough to replace all existing graphics with optimized SVGs, or do we need to change anything in particular in our codebase? If simple replacement works, I'll tackle this.
