### ISSUE TITLE
Use Realm as Database [$30]

### ISSUE THREAD

**Issue by larsgrefer** [CellularPrivacy/Android-IMSI-Catcher-Detector#655]
https://realm.io/docs/java/latest/

**Comment by SecUpwN** [comment]
Thanks for your suggestion. Would that help us finally solving the almost completed #215?

**Comment by agilob** [comment]
> JDK version >=7 

We're on ADK 16 which is JDK6?

**Comment by larsgrefer** [comment]
Yes, i think it would help

**Comment by SecUpwN** [comment]
>Yes, i think it would help

Thanks for answering, @larsgrefer. I guess I have to clarify my question regarding #215: Will this help finishing the last bits and pieces to complete #215, or do we have to re-craft the whole database? Don't you think it would be much better if you would first have a look at what is missing to complete the database overhaul and then see how we can transfer that work into Realm, if that eases up development?

**Comment by larsgrefer** [comment]
I think using realm is more a complete re-craft than finishing some last bits and pieces

Realm does not use SQL and is more object-orientated (you just store and load POJO's)

**Comment by SecUpwN** [comment]
>I think using realm is more a complete re-craft than finishing some last bits and pieces

So we'd effectively have to re-craft the whole database once more, re-invent the wheel? If you folowed the Issue for our other "major database overhaul", you see which pain the ass that was and still is. What would be the real advantage and how "easy" would it be to move to Realm? I guess all diagrams have to be re-drafted as well? Not sure if it is worth throwing away all our previous work on the database. @He3556 please add your thoughts.

**Comment by larsgrefer** [comment]
@SecUpwN Do we have an overview what kinds of objects we are currently saving in the database or want to save in the Database?

preferably UML class diagramms or POJO's?

**Comment by SecUpwN** [comment]
>Do we have an overview what kinds of objects we are currently saving in the database or want to save in the Database?

@larsgrefer, please try [Technical Overview](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Technical-Overview). Thanks.

**Comment by SecUpwN** [comment]
@larsgrefer, please have a look at [Sponsors](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector#sponsors). I don't know what your plan is and who shall re-write the database stuff yet another time, so I am wondering if the DB experts of our sponsors might help here?

**Comment by Nordlenning** [comment]
http://bit.ly/1YgV7Pq

**Comment by SecUpwN** [comment]
@Nordlenning, I've already manually edited the thread title to display the current bounty there. When @larsgrefer merges this and adds something like `fixes #215` and you accept that, he'll get the bounty.

**Comment by Nordlenning** [comment]
"I've already manually edited the thread title to display the current bounty there"
Sorry @SecUpwN But I don,t see any edited title on issue  655

But I do on bountysource. As far as I see Issue 655 & 215 different issues both with bounties.
Did you look at the link ? http://bit.ly/1YgV7Pq

I'll Leave it with that.

**Comment by Nordlenning** [comment]
:+1:

**Comment by SecUpwN** [comment]
>Sorry @SecUpwN But I don,t see any edited title on issue 655

@Nordlenning, you were right. I am currently talking to the Bountysource support about this Issue.

**Comment by Nordlenning** [comment]
& what did they say ?  No changes so far = less chance of developer attraction & Bounty donaters i guess. I have received NO answer from them so far.

**Comment by Nordlenning** [comment]
I would like @larsgrefer to make a claim on this bounty. Thank you
http://bit.ly/1YgV7Pq
