### ISSUE TITLE
Collect bug-reports at runtime

### ISSUE THREAD

**Issue by larsgrefer** [CellularPrivacy/Android-IMSI-Catcher-Detector#659]
Suggestion: https://fabric.io/kits/android/crashlytics

**To-Do added by SecUpwN:**
- [x] Implement runtime bugcollector that sends stracktraces and as few personal data as possible
- [ ] Under menu `Debugging` do not directly show the running log, but ask the user to select between:

```
[  ] Automatically send debug stacktraces
     (preferred option for better bugfixing)
[  ] Create offline debugging logfile
     (remove sensitive data before posting)
```

If a user selects the second choice, our app should **not** send _any_ bug reports through the web and just reveal the debugger with moving logs as currently shown. We also need a way to change the choice.
##

**Comment by SecUpwN** [comment]
We're currently using [Coverity Scan](https://scan.coverity.com/projects/3346), shouldn't that be good enough?

**Comment by larsgrefer** [comment]
Coverity Scan performs static analysis at compile-time.
Crashlytics would inform us about Crashes (Exceptions) at runtime.

**Comment by SecUpwN** [comment]
>Crashlytics would inform us about Crashes (Exceptions) at runtime.

One of our **main principles** we follow, is to craft our app in a way so that it does not phone home without explictly asking the user. Keep in mind that AIMSICD is mainly used by paranoid privacy geeks. ;-)

Collecting debugging data of users has been discussed extensively in #511 already, please have a read. Previous versions of our app included a hard-coded email address (which we changes several times) where users could submit their bug reports manually via the button `Debugging`. We quickly learned the hard way that even prompting the users to explain their problems did not help receiving hundreds of useless "bug reports" and "support requests", therefore we need to find a bug report system that is:

* Non-invasive (remove email function in `Debugging` and make it a checkable option `Send Crashes`)
* Not calling home until this option has been checked and *only* send real *non-identifying* crash data
* Not listed by F-Droid as an [Antifeature](https://f-droid.org/wiki/page/Antifeatures) (since our app will then likely get uninstalled by privacy geeks)
* Idiot-proof and working without any user interaction (execpt turning it on, could be asked via #181)
* Is open source, well established and completely free to use, preferrably not conflicting with GPL

Another doubt: Crashlytics/Fabric is owned by Twitter. The [Fabric Terms](https://fabric.io/terms) permit disclosure of bug data:

>Twitter shall not disclose Developer Data to any third party; provided, however, that **Twitter shall have the right to disclose any such information (i) if Twitter believes that such disclosure is reasonably necessary to comply with any applicable law, regulation, legal process, or governmental request,*** (ii) to any third-party service provider that performs services on behalf of Twitter subject to confidentiality obligations consistent with this Agreement, or (iii) if it is or becomes available to the public without breach of this Agreement by Twitter.

**Comment by larsgrefer** [comment]
@SecUpwN We could enable this feature: https://docs.fabric.io/android/crashlytics/advanced-setup.html#using-the-privacy-dialog

**Comment by SecUpwN** [comment]
Not sure what a privacy dialog helps when Twitter itself is having contracts with the CIA.
What's the difference to [Bugsnag](https://github.com/bugsnag/bugsnag-android)? Is there a comparison of such suites somewhere?

**Comment by larsgrefer** [comment]
Bugsnag should be good too

**Comment by smarek** [comment]
Well we can always anonymize reports (usually they include a lot of personal identifiable info), and I'm against using private services (binary libraries, private databases), we can work out something based on open-source hosting and open-source android bug reporting solution, back in the days I've used ACRA (https://github.com/ACRA/acra), don't know if it's still usable today

**Comment by SecUpwN** [comment]
>back in the days I've used ACRA (https://github.com/ACRA/acra), don't know if it's still usable today

It is being actively developed and maintained. As you can see, there's been an extensive discussion about in #511, even its developer @william-ferguson-au chimed in that discussion at https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/511#issuecomment-119443768. I am closing #511 in favor of this Issue now, this one is in better shape. @larsgrefer, I'm having difficulties on the decision which service to use, simply because there are so many of them. Crashlytics, Bugsnag, ACRA - I'm still hoping to find some good comparison on the web so that we can stick with one service.

**Comment by larsgrefer** [comment]
@SecUpwN https://bugsnag.com/blog/bugsnag-loves-open-source

**Comment by larsgrefer** [comment]
One more argument why we need runtime bugreports: #688

**Comment by SecUpwN** [comment]
>@SecUpwN https://bugsnag.com/blog/bugsnag-loves-open-source

Great. But why the hell does @Bugsnag have [pricing](https://bugsnag.com/pricing) if they love open source?

**Comment by larsgrefer** [comment]
@SecUpwN Because they want you to pay for their service if you aren't open source

**Comment by SecUpwN** [comment]
>Because they want you to pay for their service if you aren't open source

Whoops, I skipped this important sentence:

>We at Bugsnag love open source. Supporting the open source community is important, so we are offering **free Bugsnag** to all open source projects!

@larsgrefer, I am about to make a decision here. What does Bugsnag better than ACRA and the others?

**Comment by agilob** [comment]
If you could only test your changes before committing and merging there would be no need for 3rd party library that spies on users.

https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/683/files#diff-c8cc2dd42271f2bf39c6aa81eb6a5529L30 <-- easy as that

**Comment by SecUpwN** [comment]
>If you could only test your changes before committing and merging to master there would be no need for 3rd party library that spies on users.

@agilob, what do you mean by "spies on users"? Do you have any indicators that it does?
@larsgrefer, I digged through their and found this part I don't like:

>Bugsnag may disclose Your data if required to do so by law or in the good-faith belief that such action is necessary to comply with state and federal laws or respond to a court order, judicial or other government subpoena, or warrant in the manner required by the requesting entity. If we receive any such request, Bugsnag will make reasonable efforts to notify You promptly.

>Bugsnag also reserves the right to disclose Your data, including messages, comments, profiles, and more that we believe, in good faith, is appropriate or necessary to take precautions against liability; enforce our Terms of Service; protect Bugsnag from fraudulent, abusive, or unlawful uses; to investigate and defend ourselves against third-party claims or allegations; to assist government enforcement agencies; to protect the security or integrity of the Bugsnag Platform; or to protect the rights, property, or personal safety of Bugsnag, our customers, or others.

In any case, I guess it is important to implement the following:

* Under menu `Debugging` do not directly show the running log, but ask the user to select between:
```
[  ] Automatically send debugging logs
[  ] Offline debugging via manual logfile
```
If a user selects the second choice, the debugger as currently shown shall appear. I updated the OP.

**Comment by larsgrefer** [comment]
Whatever bug reporting tool we want to use has to be configured in a way to send as less personal data as possible. We are only interested in stacktraces but not in full logs.

**Comment by SecUpwN** [comment]
>Whatever bug reporting tool we want to use has to be configured in a way to send as less personal data as possible. We are only interested in stacktraces but not in full logs.

@larsgrefer, not sure that is possible with Bugsnag, currently digging [their Docs](https://bugsnag.com/docs). OP updated.

**Comment by larsgrefer** [comment]
@SecUpwN If the user doesn't want the app to send anything we could just return false here: https://bugsnag.com/docs/notifiers/android#beforenotify

**Comment by SecUpwN** [comment]
>If the user doesn't want the app to send anything we could just return false here

Thanks for telling me, but I'm still not convinced that Bugsnag is the tool we should be integrating. Besides the fact that they'll hand out stuff to governments, I do not trust any U.S. storage servers.

What I am essentially looking for is some service made for privacy tinfoil-projects like ours. Still searching.

**Comment by larsgrefer** [comment]
The most secure solution would be to call [`Thread.setDefaultUncaughtExceptionHandler()`](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDefaultUncaughtExceptionHandler%28java.lang.Thread.UncaughtExceptionHandler%29) in order to supply our own implementation of [`Thread.UncaughtExceptionHandler`](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.UncaughtExceptionHandler.html) which does what ever we want

**Comment by snmaynard** [comment]
I'm from bugsnag and wanted to provide some context here - you can always mention me if anyone has specific questions.

Our android notifier is actually open source at https://github.com/bugsnag/bugsnag-android and I would encourage you to take a look at the code to see what information we capture. I'd highlight https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/DeviceData.java#L148 as interesting to you.

As our notifiers are open source you can definitely fork and adjust them to really strip things back to the bare minimum that you would find useful to capture, pulling it back as far as only sending the stacktrace if thats what you would like to do. Easiest way to do that quickly would be to empty the toStream methods like https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/DeviceState.java#L49 Some of the device level stats can be very useful when figuring out low memory/os specific crashes - but you can fork the notifier and explicitly opt in to things and let your users know in the dialog what information is transmitted.

As mentioned previously we are free for open source - just contact support@bugsnag.com when you are ready to go and we'll get you moved over to a free plan.

**Comment by SecUpwN** [comment]
>I'm from bugsnag and wanted to provide some context here - you can always mention me if anyone has specific questions.

Thanks for chiming into this Issue @snmaynard, this conveys great customer support! ;-)

>As our notifiers are open source you can definitely fork and adjust them to really strip things back to the bare minimum that you would find useful to capture, pulling it back as far as only sending the stacktrace if thats what you would like to do.

Is there a way to **not** strip down your code to the bare minimum, but configure the collection of *just* the stacktrace via the dashboard or some extra code snipped added to some file of our app? If we empty the `toStream` methods, will we still be collecting useful data to debug our app as best as possible?

>Some of the device level stats can be very useful when figuring out low memory/os specific crashes - but you can fork the notifier and explicitly opt in to things and let your users know in the dialog what information is transmitted.

I've actually signed up today to have a glance at the bug collection dashboard, was about to push the integration to a separate branch but deleted our account again after reading the bugsnag privacy policy: It seems as if bugsnag hands out data to governments upon request. Since we're very privacy-minded people and political activists and paranoid tinfoil hats are using our app, I feel that is my duty to make sure no personal identifyable data is leaking via our app and the people using it do not get in trouble.

**Comment by snmaynard** [comment]
> Is there a way to not strip down your code to the bare minimum, but configure the collection of just the stacktrace via the dashboard or some extra code snipped added to some file of our app? If we empty the toStream methods, will we still be collecting useful data to debug our app as best as possible?

I think that forking and removing whatever data you don't want to send is the best option. The changes would probably be only to remove the device id, but I'd encourage you to look at what gets sent and audit that. If you send a couple of test exceptions you can get a good look at what gets sent. We display all the information we record in our ui, so it should be easy enough to make sure you are comfortable with what gets sent.

**Comment by SecUpwN** [comment]
>I think that forking and removing whatever data you don't want to send is the best option.

Ok dudes, I think this approach is as privacy-aware as can be. The repository with the modified bugsnag for our project will be located at https://github.com/SecUpwN/bugsnag-android. Thanks @snmaynard!

**Comment by larsgrefer** [comment]
@SecUpwN 
>[Shoot an email](mailto:opensource@bugsnag.com) to us and link us to your repository to get your account set up. If you're so inclined, you can tell us a little bit about your open source project, and we'll tweet about it! 

https://bugsnag.com/blog/bugsnag-loves-open-source

**Comment by SecUpwN** [comment]
Just a short update: I've sent them an email yesterday, I guess they'll respond tomorrow at the latest.

**Comment by TPS** [comment]
Just FYI to follow-up on [an earlier comment](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/659#issuecomment-162424006):
>*Not listed by F-Droid as an [Antifeature](https://f-droid.org/wiki/page/Antifeatures) (since our app will then likely get uninstalled by privacy geeks)

According to recently update to https://gitlab.com/fdroid/fdroidclient/raw/HEAD/CHANGELOG.md, even F-droid client includes ACRA, so I figure, if configured the way it does, it shouldn't red-flag as Anti-feature.
>#### 0.98 (upcoming release)
* Add opt-in crash reporting via ACRA


N.B.:  This just FYI, as it seems you all are pretty set on BugSnaq!

**Comment by SecUpwN** [comment]
>N.B.: This just FYI, as it seems you all are pretty set on BugSnaq!

Thanks for your input, @TPS. We've already decided to use a customized version of `bugsnag` maintained at https://github.com/freefair/advanced-bugsnag-android which will only collect privacy-aware stack-traces to improve our app. Furthermore, their lovely support just made them win our election.

**Comment by AlexNab** [comment]
@SecUpwN as you asked me, as a crash reporting solution I would recommend to use [Crashlytics](https://try.crashlytics.com/) (it's a part of [Fabric](https://fabric.io) kit now). I used it in a couple of projects (even before joining Twitter), and it's really good. And it becomes better and better with time. 

In addition to app crashes, Crashlytics can also report internal caught exceptions. 
Also what is important, especially for a project like SecUpwN, is that Crashlytics is completely free, without paid tiers as BugSnag, HockeyApp and others.

Fabric can also provide [useful services](https://get.fabric.io/kits) like beta distribution, analytics, A/B testing, etc. 

Hope this helps.

**Comment by SecUpwN** [comment]
Thanks for answering, @AlexNab. Please read my previous message, we've already decided on this. ;-)

**Comment by rugk** [comment]
FYI Mozilla also uses their own crash reporter in Fennec (better knows as Firefox for Mobile).
