### ISSUE TITLE
App quits when retrieving OpenCellID key

### ISSUE THREAD

**Issue by lop1** [CellularPrivacy/Android-IMSI-Catcher-Detector#691]
If in preferences you try to get an opencellID key you got : 
"Android IMSI-Catcher Detector stopped"

release 0.1.37 alpha
galaxy S4 mini
stock rom rooted ( COJ1 )

**Comment by SecUpwN** [comment]
Possibly related to #688. Please wait for this to be fixed. Thank you.

**Comment by SecUpwN** [comment]
@larsgrefer, this bug is present again after your latest changes.

**Comment by mimi89999** [comment]
I can't reproduce it.

**Comment by mimi89999** [comment]
I think this was fixed in https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/commit/76bc831faa7fe8514cd4663e82753a2a7a9b170d
