### ISSUE TITLE
Fail to open folder errors

### ISSUE THREAD

**Issue by licaon-kter** [CellularPrivacy/Android-IMSI-Catcher-Detector#698]
v0.1.37-alpha

Logcat: https://gist.github.com/licaon-kter/e95adbcd83992c5e200a

Tested w/ or w/o XPrivacy whitelisting.

**Comment by SecUpwN** [comment]
@licaon-kter, please [compile from source](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Building) test if this bug vanished with the current `development` branch.

**Comment by licaon-kter** [comment]
Umm, build it, open it, About window opens, press back arrow, app closes.

Any idea?

Android Studio 2.0 preview

**Comment by SecUpwN** [comment]
@licaon-kter, please verify the presence of this bug in our current release, otherwise plrease close it.

**Comment by licaon-kter** [comment]
Still getting:
```
E Vold    : Failed to find mounted volume for /storage/sdcard1/Android/data/com.SecUpwN.AIMSICD/files/
W ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.SecUpwN.AIMSICD/files
```

**Comment by SecUpwN** [comment]
@CellularPrivacy/database, would you please be so kind and have a closer look at this Issue?

**Comment by mimi89999** [comment]
@SecUpwN @licaon-kter I can't reproduce it in the latest version built from source.

**Comment by mimi89999** [comment]
The only thing I noticed, was that I had to give AIMSICD root for this to work.

**Comment by SecUpwN** [comment]
>The only thing I noticed, was that I had to give AIMSICD root for this to work.

@He3556, is it normal that our app needs ROOT access to open folders on the SD Card? Not sure..

**Comment by licaon-kter** [comment]
It already has root, afaics.
Unfortunately I don't remember in what way this impacted the app in the first place, so while I see those in the logs still, I wonder what is actually broken because of it.

On that note I can't upload OCID data as I always get am error:
```
D Injector: Injection of com.secupwn.aimsicd.utils.RequestTask@1bbf22dd took 6ms
E Vold    : Failed to find mounted volume for /storage/sdcard1/Android/data/com.SecUpwN.AIMSICD/files/
W ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.SecUpwN.AIMSICD/files
I AIMSICDDbAdapter: Checking for db first install this will throw an error on install and is normal
D AppAIMSICD: BaseTask addTask activity:com.secupwn.aimsicd.AIMSICD
V AppAIMSICD: BaseTask added:com.secupwn.aimsicd.utils.RequestTask@1bbf22dd
I RequestTask: OCID upload data prepared - false
```
But I'm not sure these are related or I need to open another issue.

**Comment by f3ndot** [comment]
Vanilla//Stock Nexus 6P Android 6.0 works from compiled source.

**Comment by SecUpwN** [comment]
@licaon-kter, please contact me via E-Mail so that I can send you a bleeding edge APK for testing.

**Comment by licaon-kter** [comment]
Logcat shows the same `E Vold` error for Firefox too, so this might be a ROM issue.

**Comment by mimi89999** [comment]
What ROM? Did you try wiping data and reflashing it?

**Comment by licaon-kter** [comment]
Xperia 5.1.1 rooted stock. No.

**Comment by mimi89999** [comment]
Maybe you have messed up with sdcard permissions?

**Comment by licaon-kter** [comment]
No sdcard in device.
No sdcard access permissions control in 5.1.1, afaik.
Xprivacy not activated (although installed).

**Comment by mimi89999** [comment]
Internal sdcard...

**Comment by licaon-kter** [comment]
Do detail what to check and how.
I can use the device, I can export/import fine from /sdcard/...

**Comment by mimi89999** [comment]
Can you read and write to /sdcard/sdcard1/Android/data?

**Comment by licaon-kter** [comment]
That's an empty folder since that needs root access (to remount as rw) to write anything in.

**Comment by mimi89999** [comment]
Why is it read-only?

**Comment by mimi89999** [comment]
Ah, yes. Here would be mounted the external sdcard if you had one... What I don't understand is why AIMSICD is trying to write to external sdcard and not to internal.

**Comment by licaon-kter** [comment]
What I don't understand is why bother writing to external since it already writes ok to internal?!

**Comment by SecUpwN** [comment]
>What I don't understand is why bother writing to external since it already writes ok to internal?!

So do we have an SD detection problem with our app? Do we need to rename and re-open this Issue?

**Comment by licaon-kter** [comment]
I'm not sure, hence it's closed.
Either both this and Firefox have the same problem or there is something else at fault (eg. my ROM/Xposed)

**Comment by mimi89999** [comment]
I will check this on my device runng cm13 with the latest version of AIMSICD compiled from source when I will be back home...

**Comment by mimi89999** [comment]
@licaon-kter Would it be a problem for you to flash CyanogenMod on your device?

**Comment by licaon-kter** [comment]
Yeah, locked bootloader.

**Comment by mimi89999** [comment]
http://developer.sonymobile.com/unlockbootloader/unlock-yourboot-loader/

**Comment by agilob** [comment]
> It already has root, afaics.

According to logs you have some problem with `su` on your device:
```
W/PackageManager( 3452): Unknown permission android.permission.ACCESS_SUPERUSER in package com.SecUpwN.AIMSICD
```

It looks like a problem with ROM, code tried to create database using context.getDatabasePath(), which should return something like `/data/data/com.asimsicd/databases/`
One walkaround could include catching exception and setting fallback directory if that one specific exception was thrown.

Another issue, possibly sdcard1/ could be a mount point of /data/data/. Could you confirm that directory does **not** exist in your system? Open a file manager and go to /storage/, list folders from this directory. Looks like ROM problem, but nothing that can't be fixed with 3 lines of code.

**Comment by mimi89999** [comment]
@agilob He has plenty of `Unknown permission` warnings. What I need to know is if it's a problem with the ROM or with the app.

**Comment by licaon-kter** [comment]
@agilob That's the old log, see my comments, it's not the same thing now. Read my other comments too regarding **/sdcard1/**.

@mimi89999 TelCo sold devices don't have that option (`Bootloader unlock allowed: No`) :-\
Both Sony and TelCo's point to each other.

**Comment by agilob** [comment]
@licaon-kter could you check the /storage/ directory for existing folders?

**Comment by mimi89999** [comment]
@licaon-karter Could you show me the fstab file in /system/etc?

**Comment by mimi89999** [comment]
@licaon-kter
> TelCo sold devices don't have that option (Bootloader unlock allowed: No) :-\

Try flashing a global / european generic firmware with flashtool.

**Comment by mimi89999** [comment]
I checked this, but I can't reproduce it.

**Comment by licaon-kter** [comment]
> Try flashing a global / european generic firmware with flashtool.

There is no know solution for `Bootloader unlock allowed: No`.

**Comment by mimi89999** [comment]
I know, but this trick might work sometimes...

**Comment by SecUpwN** [comment]
Folks, what are you guys discussing? How to [root the phone](http://xda-developers.com/root)?

**Comment by licaon-kter** [comment]
Nope, I has root, no CM13 for me but plenty of root.
Anyway, any news regarding this?

**Comment by SecUpwN** [comment]
>Anyway, any news regarding this?

@licaon-kter, please [compile](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Building) the latest `development` branch and test if this Issue still persists.
