### ISSUE TITLE
IMSI-Catchers cause power drain issue?

### ISSUE THREAD

**Issue by rjh427** [CellularPrivacy/Android-IMSI-Catcher-Detector#70]
I confess to not following all the discussions here as closely as I should, but this recently came across the cypherpunks list - I thought it was relevant:

"In a previous note on Cypherpunks, I believe I read that exposure to one of these Stingrays causes a cell phone to emit its signal at maximum power, causing a battery drain.  This suggests that a simple Stingray-detector could be built, using an old cell-phone, a power-supply with a current-limit-detector connected to an alarm.  If the cell phone emits maximum RF-signal, it will use a considerable DC power, which could be set to trigger the DC-current alarm.  (Am I correct in thinking that the old cell-phone doesn't even have to be 'active', meaning that it doesn't have to have a contracted service associated with it?)"

So my thought is, either as an augment to what is already being tested for or as an alternate test that may or may not indicate IMSI-Catchers in the area, if power draw suddenly spikes and stays spiked then I for one would want some sort of notification.

If this has already been or is already being addressed, just close this issue and carry on.

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.
