### ISSUE TITLE
Status not switching to IDLE when disabling detection

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#716]
Taken from https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/711#issuecomment-167716002, our app currently shows status `OK` or `MEDIUM` even when disabling detections by pressing `Toggle Attack Detection` in `Navigation Drawer`. It should switch to `IDLE`.

**Comment by VladThodo** [comment]
@SecUpwN  I can try to fix this,but I need a little bit of explainations..
Should the icon switch to IDLE only when cell monitoring is disabled? ;)

**Comment by SecUpwN** [comment]
> I can try to fix this,but I need a little bit of explainations..

Wonderful to see you're grabbing more Issues you feel you can fix! :+1:

>Should the icon switch to IDLE only when cell monitoring is disabled? ;)

Status `IDLE` should only appear in the following cases:

* 1. When our app has been started the very first time and is not fully set up.
* **2. When button `Toggle Attack Detection` has been disabled.**
* 3. When our app is loading (which would essentially be point 1).

So the solution here would be switch to `IDLE` state when `Toggle Attack Detection` is turned off.

**Comment by SecUpwN** [comment]
@VladThodo, I'm afraid your pull request did not fully fix that Issue. I'm just getting a white Status Icon (likely due to me currently using Android 6+) and the Status does not change when turning it off. Reopened.

**Comment by larsgrefer** [comment]
@SecUpwN The material design says, status bar icons should be white-only (we discussed this in #512)

I assume this happened because @VladThodo used the `NotificationCompat` class

**Comment by VladThodo** [comment]
@larsgrefer Do you mean that I should use the normal 'Notification' class?

**Comment by SecUpwN** [comment]
>The material design says, status bar icons should be white-only (we discussed this in #512)

@larsgrefer, true. But when **unchecking** `Toggle Attack Detection` then the status should change to `IDLE`, which the pull request of @VladThodo was aiming to accomplish. But that does not happen yet.

>Do you mean that I should use the normal 'Notification' class?

Yes, please do that for now until we have finished decision on #512. Would be lovely if you could check why your pull request did not chnage the status properly and then send another pull request if possible.

**Comment by VladThodo** [comment]
@SecUpwN I'll try to do it when I get home and also check the 'if' statements 'cause I think there's the problem

**Comment by VladThodo** [comment]
@SecUpwN @larsgrefer  I did a little bit of reasearch and  using the "normal" `Notification` class won't do the trick on 5.0 an higher..the only workaround for this is to change the target SDK version to '20' wich isn't recommended at all..so I guess we can't fix this so easy

**Comment by larsgrefer** [comment]
@VladThodo Our `targetSdk` is currently `19` for exact this reason

**Comment by larsgrefer** [comment]
@SecUpwN @VladThodo I'm currently working on a solution in order to get a pretty white icon and a targetSdk of at least 22

**Comment by SecUpwN** [comment]
>I'm currently working on a solution in order to get a pretty white icon and a targetSdk of at least 22

Great! What do you mean by !pretty white Icon", @larsgrefer?

**Comment by larsgrefer** [comment]
@SecUpwN Only the white cell-tower shape on a transparent background (without a circle around)

I'll provide a PR with screenshots once I'm ready
