### ISSUE TITLE
Request MNC as optional parameter

### ISSUE THREAD

**Issue by jawz101** [CellularPrivacy/Android-IMSI-Catcher-Detector#732]
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/434#issuecomment-168078594

As many other geeks, I am cheap and my Mobile Network provider is one of those no contract Mobile Virtual Network Operators
https://en.wikipedia.org/wiki/Mobile_virtual_network_operator

_(ex: in the United States some major MVNOs are Ting, Virgin Mobile, Straight Talk, Net10, Tracfone, Boost Mobile, Cricket, etc.  The UK has a bunch as well)_.

The OpenCellID website returns 0 results if the MNC of my cheap carrier is passed.  It does piggyback off of a major carrier's towers so I assume if I could manually specify its MNC code it would work or just optionally omit the MNC from the API request altogether?

As explained in the github comment above I'm able to use a browser and download tower information if I remove the MNC parameter from the API call to OpenCellID.org because they apparently don't know my cheap MVNO network code.
##

**Comment by SecUpwN** [comment]
I guess this would only cause more trouble when taking https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/434#issuecomment-168154647 into account.

**Comment by jawz101** [comment]
Well if I'm on an MVNO which piggyback's off of AT&T's network would I not use the same towers as AT&T?
