### ISSUE TITLE
Neighboring Cells show unknown Type

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#746]
There seems to be a bug with detecting the Neighboring Cells as they show `Type: 0 - Unknown`.

**Comment by f3ndot** [comment]
Can reproduce on my Nexus 6P device with stock Android 6.0.1, unrooted

**Comment by SecUpwN** [comment]
Tested with Buildozer Build `B-528` (Git SHA-Hash `78400ae`) again and this seems fixed.
