### ISSUE TITLE
Automatic versionName not working

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#781]
@larsgrefer, I'm sorry that you're having to code so much, but I just noticed that our app is displaying its version name as `unspecified-normal`. That causes more trouble when publishing it elsewhere. Please see if you can fix this in the upcoming days. No hurry. Already published `v0.1.40.1-alpha` on all stores.

**Comment by SecUpwN** [comment]
@larsgrefer, thanks for the quick fix! Is it normal that our Buildozer builds still say `unspecified-normal`?

**Comment by SecUpwN** [comment]
I am sorry having to re-open this, @larsgrefer. It appears that the Issue is still present.

**Comment by SecUpwN** [comment]
@larsgrefer, the Buildozer version now looks like this: `Version: -SNAPSHOT-normal`.
How will releases be named created with Travis-CI? Will it be `Version: 0.1.42-alpha-normal`?

**Comment by larsgrefer** [comment]
The Buildozer log shows this:
>49: No git tag found
50: No git tag found

It seems like buildozer does not fetch the tags when cloning the repo.

so when the gradle plugin tries to find out what the latest tag is, it gets an empty result

**Comment by SecUpwN** [comment]
>It seems like buildozer does not fetch the tags when cloning the repo.

@Buildozer, would you please be so kind to fix this and post an official statement here? Thank you!

**Comment by larsgrefer** [comment]
@SecUpwN 

we could try running `git fetch --tags` ourselfs during the build

**Comment by SecUpwN** [comment]
>we could try running `git fetch --tags` ourselfs during the build

If that does not cripple F-Droid builds or prevent proper development, it sounds like a good solution.

**Comment by SecUpwN** [comment]
@larsgrefer, I just received the following reply via E-Mail from @ijansch:

>Hi, Buildozer does not check out the tag, it checks out the latest version from a branch. It's unclear what your request regarding tags is.

**Comment by larsgrefer** [comment]
@SecUpwN It's not about what's checked out by buildozer but what's fetched

**Comment by larsgrefer** [comment]
`git tag --list` returns an empty result when run on buildozer

**Comment by larsgrefer** [comment]
running `git fetch --tags` during the build lets `git tag --list` work correctly, but for some reason `git describe --abbrev=0 --tags --match v*` still returns an empty result

**Comment by larsgrefer** [comment]
@SecUpwN `git fetch --unshallow --tags` solves the problem on buildozer

solved in 745b12a2e921872885d3b3f964b3792b3832dda9
