### ISSUE TITLE
Move project into new organization

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#814]
[![Organizations](https://cloud.githubusercontent.com/assets/391331/6141962/a321a37a-b162-11e4-8452-06965ee672e4.png)](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/814)

In relation to #628, I've been thinking a lot about moving this project into an official [ organization](https://github.com/blog/674-introducing-organizations), just like @SMSSecure and @LibreSignal. See the [difference between user and organization accounts](https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/).

**Main Advantages:**

* Repository management
* Fine-grained permissions
* Focused dashboard

---

With this Issue, I'd like **your suggestion for a great name of our new organisation** (which I will personally create and move the project there later on). The old project link will still work and redirect to our new organisation, thus all links on the web will stay valid. The new link to our project will look like this:

`https://github.com/[NEW_ORGANISATION_NAME]/Android-IMSI-Catcher-Detector/`

We've been using the following names in official correspondence and should consider using those:

* AIMSICD
* AIMSICD Privacy Project

**Other possibilities:**

* PrivacyLab
* PrivacyForce
* PrivacyDefense
* SecurityDefense
* SecurityForce
* DefenseLab
* NetworkDefense
* SpyDefense
* SmartPrivacy
* [...]

Since we'd like to continue our strive towards professionalism, feel invited to drop your own suggestion!

---

**My checklist to complete this Issue:**

- [x] Announce this Issue via our Twitter
- [x] Decide on new organisation name
- [x] Create new organization, add team
- [x] Set right permissions on members
- [x] Move project into new organization
- [x] Make sure all file links are working
- [x] Fix builds (Travis-CI, F-Droid, Buildozer, etc.)

**Comment by mimi89999** [comment]
I think creating an organization for this project is a good idea.
For the name:
If the organization would be only related to AIMSICD, then a name containing AIMSICD should be good.

**Comment by SecUpwN** [comment]
Thanks for your reply, @mimi89999. Yes, the organization will mainly be used for this project, but should be easy to remember as well. Not sure if it makes sense having the terms "Privacy" or "Security" in it. Hoping for a reply of @larsgrefer, @he3556 and @f3ndot soon.

**Comment by agilob** [comment]
I'm full for it. It will mostly solve a problem of showing who has direct access to the repository and can directly push to master branch. Currently it's not visible (or I can't find it on github) and it creates a trust issue. Ones account can be compromised and used to push bad code and make a new release directly to automated releases like travis and fdroid. That would essentially compromise the project and releases from travis.

**Comment by mimi89999** [comment]
Members and owners of Github organizations can hide their visibility...

**Comment by f3ndot** [comment]
We should avoid choose AIMSICD as an organization name should we ever want
to release a new app or tool under the same branding.

Cellular Privacy Project?

I'm happy with whatever y'all choose as the name, but definitely the
organization is a good idea.

On Mon, Mar 14, 2016, 10:20 AM mimi89999 <notifications@github.com> wrote:

> Members and owners of Github organizations can hide their visibility...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/814#issuecomment-196327577>
> .
>
-- 
Justin Bull
PGP Fingerprint: E09D 38DE 8FB7 5745 2044 A0F4 1A2B DEAA 68FD B34C

**Comment by SecUpwN** [comment]
>We should avoid choose AIMSICD as an organization name should we ever want to release a new app or tool under the same branding.

Thanks, @f3ndot. You're right, a broader name would fit better. But `Cellular Privacy Project` is a bit too long. We need something shorter. How about `CellularPrivacy`, `CellPrivacy` or `SmartPrivacy`? Too bad that noone is interested adding good suggestions, even after announcing it via Twitter.

**Comment by He3556** [comment]
i think we should avoid AIMSICD, too
I like "CellularPrivacy" - the short version "CellPrivacy" doesn't hit the point, i think. 
"MobilePrivacy" would be another possibility. But CellularPrivacy does describe it better, as we care about the mobile network in the first place and not about the mobile device.

**Comment by f3ndot** [comment]
@secupwn open source is hard! People have busy lives and things take time.

I say after a few weeks, just decide what you think is best and choose a
name based off what's recommended or suggested here.

On Tue, Mar 15, 2016, 4:23 PM MPR <notifications@github.com> wrote:

> i think we should avoid AIMSICD, too
> I like "CellularPrivacy" - the short version "CellPrivacy" doesn't hit the
> point, i think.
> "MobilePrivacy" would be another possibility. But CellularPrivacy does
> describe it better, as we care about the mobile network in the first place
> and not about the mobile device.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/814#issuecomment-197005643>
>
-- 
Justin Bull
PGP Fingerprint: E09D 38DE 8FB7 5745 2044 A0F4 1A2B DEAA 68FD B34C

**Comment by SecUpwN** [comment]
Thanks for your soothing words, @f3ndot. Helps a lot getting a bit encouragement on such difficult decisions. Which one do you personally like better: `CellularPrivacy` or `MobilePrivacy`? @larsgrefer, should we rename our current package name `com.SecUpwN.AIMSICD` as well?

**Comment by mimi89999** [comment]
@SecUpwN Changing the package name will cause issues when updating...

**Comment by f3ndot** [comment]
I like CellularPrivacy because we're confused on cell towers. It speaks to
the technical nature of what we're defending

On Wed, Mar 16, 2016, 4:09 PM mimi89999 <notifications@github.com> wrote:

> @SecUpwN <https://github.com/SecUpwN> Changing the package name will
> cause issues when updating...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/814#issuecomment-197524853>
>
-- 
Justin Bull
PGP Fingerprint: E09D 38DE 8FB7 5745 2044 A0F4 1A2B DEAA 68FD B34C

**Comment by SecUpwN** [comment]
>Changing the package name will cause issues when updating...

Yes, I've seen the trouble in https://github.com/LibreSignal/LibreSignal/issues/12.

>I like CellularPrivacy because we're focused on cell towers. It speaks to the technical nature of what we're defending

Thanks again, @f3ndot. I'll be sleeping a night about that and let you know my decision soon.

**Comment by larsgrefer** [comment]
>should we rename our current package name `com.SecUpwN.AIMSICD` as well?

Do you mean the [package name or the applicationId](http://tools.android.com/tech-docs/new-build-system/applicationid-vs-packagename)?

Our current package Name is `com.secupwn.aimsicd` and can be changed without problems.

Our current applicationId is `com.SecUpwN.AIMSICD`. If we change this, we will create a _new_ app.

**Comment by He3556** [comment]
Maybe it is better to keep the name AIMSICD as package name and app id. I think it would be work for nothing to change it - and think about the postings everywhere in the web. It would also confuse peope if we change it now.

**Comment by SecUpwN** [comment]
>Maybe it is better to keep the name AIMSICD as package name and app id. I think it would be work for nothing to change it - and think about the postings everywhere in the web. It would also confuse peope if we change it now. 

I fully agree. So we're basically just moving into a better to maintain organization. Does everyone agree with the proposed name `CellularPrivacy` or did you come up with a shorter or better fitting name?
