### ISSUE TITLE
Multiple force closes on database requests

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#816]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

---AIMSICD WIP  v0.1.41-alpha , Sony Experia V lt25i Lollipop Cy.

From the main (top) border rigth side menu I go to preferences.
Then I Ask for OpenCell API Key : AIMSICD Stops.
AIMSICD keeps running in the background, 

Same happens when I try to use "add new strings": AIMSCID stops.
Same happens when I try to use "Delete SMS" : AIMSCID stops.
Downloading OCID Data from Map view, downloading icon(circle) 
keeps turning after OCID Data is downloaded.
Still unable to upload to OCID database. 

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

---Same as above 

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by mimi89999** [comment]
Same issue on my Samsung galaxy S4 mini with CM13. I will add the log when I will have access to ny PC.

**Comment by mimi89999** [comment]
https://gist.github.com/mimi89999/4ee359308a2c316de1cf

**Comment by SecUpwN** [comment]
@larsgrefer, could you please be so kind and have a look at the logfiles posted here? Thank you!

**Comment by rmenessec** [comment]
I don't know if it's directly related, but AIMSICD FCs immediately on attempting to request an API key. Nexus 6, Android 6.0 (MMB29V).

**Comment by licaon-kter** [comment]
Same: https://gist.github.com/licaon-kter/7d5194dcd8115c9cc0b1

**Comment by mimi89999** [comment]
First crash:
03-21 20:28:49.159 28021 28021 E AndroidRuntime: FATAL EXCEPTION: main
03-21 20:28:49.159 28021 28021 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 28021
03-21 20:28:49.159 28021 28021 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, com.android.systemui=overlay:system}
03-21 20:28:49.159 28021 28021 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown component: com.secupwn.aimsicd/com.secupwn.aimsicd.activities.OpenCellIdActivity
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1624)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2676)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3930)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3890)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4213)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4181)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1012)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-21 20:28:49.159 28021 28021 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Another crash:
03-21 20:28:51.889 28125 28125 D AIMSICD : StatusWatcher received status change to OK, updating icon
03-21 20:28:51.926 28125 28125 D AndroidRuntime: Shutting down VM
03-21 20:28:51.929 28125 28125 E AndroidRuntime: FATAL EXCEPTION: main
03-21 20:28:51.929 28125 28125 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 28125
03-21 20:28:51.929 28125 28125 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, com.android.systemui=overlay:system}
03-21 20:28:51.929 28125 28125 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at com.secupwn.aimsicd.fragments.DeviceFragment.updateUI(DeviceFragment.java:132)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at com.secupwn.aimsicd.fragments.DeviceFragment.access$200(DeviceFragment.java:47)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at com.secupwn.aimsicd.fragments.DeviceFragment$1.onServiceConnected(DeviceFragment.java:109)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1224)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1241)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-21 20:28:51.929 28125 28125 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-21 20:28:51.931   592  7142 W ActivityManager:   Force finishing activity com.SecUpwN.AIMSICD/com.secupwn.aimsicd.AIMSICD

**Comment by mimi89999** [comment]
@SecUpwN In a recent commit, in the manifest file, you changed `package="com.secupwn.aimsicd"`, but you didn't change the valuses under `activities` in the same file.

**Comment by SecUpwN** [comment]
>In a recent commit, in the manifest file, you changed `package="com.secupwn.aimsicd"`, but you didn't change the valuses under `activities` in the same file.

Do you expect this to be the cause, @mimi89999? I've invited you to check and improve our code a bit. ;-)

**Comment by mimi89999** [comment]
I don't know (and after checking I doubt it), but I would check the commits changing the package name... And actually why did you change this?

**Comment by SecUpwN** [comment]
>I don't know (and after checking I doubt it), but I would check the commits changing the package name...

Please provide a pull request to fix this if you see it to be a necessity.

>And actually why did you change this?

Please see #812, which fixed #810.

**Comment by mimi89999** [comment]
Reverting #812 fixes the issue, but I need to find another way to fix this....

**Comment by mimi89999** [comment]
https://github.com/mimi89999/Android-IMSI-Catcher-Detector

**Comment by SecUpwN** [comment]
>Reverting #812 fixes the issue, but I need to find another way to fix this....

@mimi89999, please refork our project and do not revert #812. We renamed the java packages to adhere to the [java naming conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) in order to make our follow common coding practices to ease up the life of developers. I cannot imagine that the whole thing is caused by just lowercasing the java package names and guess this Issue needs a better tracedown.

**Comment by mimi89999** [comment]
#821

**Comment by mimi89999** [comment]
`W/PushTextSendJob( 4385): org.whispersystems.textsecure.api.crypto.UntrustedIdentityException: Untrusted identity key!`

**Comment by Nordlenning** [comment]
v0.1.41-alpha compiled from source 30.03.16 22:00

From the main (top) border right side menu I go to preferences.
Then I Ask for OpenCell API Key : AIMSICD still "force-close"
AIMSICD keeps running in the background.

"add new strings": Works "Solved".
"Delete SMS" : Works "Solved".
 Still unable to upload to OCID database. "Not Solved"

**Comment by mimi89999** [comment]
I will check this.

**Comment by SecUpwN** [comment]
>I will check this.

Thanks for your engagement, @mimi89999! Please re-open this Issue if it still persists.

**Comment by mimi89999** [comment]
I can confirm that this issue still exists.

**Comment by mimi89999** [comment]
@SecUpwN I would like to reopen this issue, but I don't have the needed permissions for that.

**Comment by mimi89999** [comment]
The error:
`03-31 16:13:02.783  5686  5686 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.SecUpwN.AIMSICD/com.secupwn.aimsicd.activities.OpenCellIdActivity}; have you declared this activity in your AndroidManifest.xml?
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3930)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3890)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4213)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4181)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1012)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-31 16:13:02.783  5686  5686 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-31 16:13:02.785   592   792 W ActivityManager:   Force finishing activity com.SecUpwN.AIMSICD/com.secupwn.aimsicd.ui.activities.SettingsActivity`

**Comment by mimi89999** [comment]
@SecUpwN I'm working on this now.

**Comment by licaon-kter** [comment]
I can confirm, not fixed.

**Comment by mimi89999** [comment]
> I can confirm, not fixed.

My PR #821 fixed this issue. Now it's a different one...

**Comment by mimi89999** [comment]
#829

**Comment by Nordlenning** [comment]
If I try to view errorlogging while I em trying to download OCID data from OCID server in Map view AIMSCID Crashes.. Only If Wifi is Connected, Other-vice not.

**Comment by mimi89999** [comment]
`03-31 17:23:37.721  9493  9493 D AndroidRuntime: Shutting down VM
03-31 17:23:37.726  9493  9493 E AndroidRuntime: FATAL EXCEPTION: main
03-31 17:23:37.726  9493  9493 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 9493
03-31 17:23:37.726  9493  9493 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, com.android.systemui=overlay:system}
03-31 17:23:37.726  9493  9493 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=3
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at java.lang.String.startEndAndLength(String.java:298)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at java.lang.String.substring(String.java:1087)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at com.secupwn.aimsicd.ui.activities.MainActivity.downloadBtsDataIfApiKeyAvailable(MainActivity.java:313)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at com.secupwn.aimsicd.ui.activities.MainActivity.selectDrawerItem(MainActivity.java:267)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at com.secupwn.aimsicd.ui.activities.MainActivity$DrawerItemClickListener.onItemClick(MainActivity.java:214)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-31 17:23:37.726  9493  9493 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

??

I will also look at that, but that's another issue.

**Comment by mimi89999** [comment]
@Nordlenning Could you post log of this error because I can't reporduce it.

I found another problem (the logcat above). The app crashes when trying to download OpenCellId if device is in airplane mode with Wi-Fi enabled.

**Comment by Nordlenning** [comment]
If I can get hold of any log yes, but AIMSICD freezes so i cant get it. Or can I ?
Uploading Picture of the event, I can repeatedly reproduce this error.

"I found another problem (the logcat above). The app crashes when trying to download OpenCellId data if device is in airplane mode with Wi-Fi enabled."

(I have the same crash without Wifi enabled too).

![crash screenshot_2016-03-31-16-17-22](https://cloud.githubusercontent.com/assets/17292772/14183100/f743c3ec-f75d-11e5-98ca-2ee500fcfcc0.png)

**Comment by mimi89999** [comment]
You can do this with `adb logcat` from a PC with the device connected.

**Comment by SecUpwN** [comment]
Thanks for all the hard work, guys. @Nordlenning, please contact me via E-Mail and I will send you an APK of the very bleeding edge `development` branch so that you canm test if #829 really solved this.

**Comment by Nordlenning** [comment]
v0.1.41-alpha compiled from source 01.04.16 07:00
Sony Experia V25lti - CM Tsubasa
 
"Ask for OpenCell API Key" Solved"
"add new strings": Works "Solved".
"Delete SMS" : Works "Solved".

Works smooth & fine 
Excellent work @mimi89999
