### ISSUE TITLE
cert pinning critical vulnerability?

### ISSUE THREAD

**Issue by javixeneize** [CellularPrivacy/Android-IMSI-Catcher-Detector#820]
Hi

I am trying to do cert pinning in my app. I have this issue reported

[Critical] <KeyStore><Hacker> KeyStore Protection Checking:
           The Keystores below seem using "byte array" or "hard-coded cert info" to do SSL pinning (Total: 1). Please manually check:
               => L/javi/cert;->a(Ljava/security/cert/X509Certificate;)Ljavax/net/ssl/SSLContext; (0x12) --->
                    Ljava/security/KeyStore;->load(Ljava/io/InputStream; [C)V

I am not using any byte array neither have the cert hardcoded. Any idea why this issue is reported?

Thanks

**Comment by SecUpwN** [comment]
>I am trying to do cert pinning in my app. I have this issue reported

@larsgrefer is this to be labelled as `SECURITY_ISSUE`, or is this one `INVALID`?

**Comment by SecUpwN** [comment]
Good evening @javixeneize, thanks for the personal E-Mail. I will quote it for completeness here:

>Hi

>No idea why this issue is reported in this github? This is related to androbugs

>Thanks

Closing this as `INVALID` since this Issue belongs into https://github.com/AndroBugs/AndroBugs_Framework/issues/4.
