### ISSUE TITLE
App crashes when some settings are accessed, including 

### ISSUE THREAD

**Issue by rugk** [CellularPrivacy/Android-IMSI-Catcher-Detector#822]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

The options "OpenCellID request API key", "Recognition pattern" and "delete SMS" cause the app to crash. (default Android message).
Unfortunately this message does not let me submit a crash report as it is sometimes possible when other apps crash.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen): 0.1.41-alpha-normal (downloaded from FDroid)
* Phone and ROM running *current* release: [Galaxy S4 (GT-I9505/jfltexx)](http://wiki.cyanogenmod.org/w/Jfltexx_Info) with Cyanogenmod 13 (nightly: cm-13.0-20160325)
* Link to logfile without identifyable data: [coming soon - is this/which log is useful in this case?]

Firewall setup:
* XPrivacy, but I've read [this](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Permissions) and AIMSICD is not restricted
* AFWall+, but everything for AIMSICD is allowed

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

1. Go to the settings.
2. Tap on **either** "OpenCellID request API key", "Recognition pattern" or "delete SMS"

What happens: App crashes.

What should happen: Let me change this option.

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

---

#### Workaround
As I cannot request the API key for Opencellid.org from the app, I looked for a way to get it from [the website](http://opencellid.org/), but I found no way to get it.
So can I somehow get this key manually? Because the "entry API key" option does not cause crashes, so I assume entering this key should work.

**Comment by Nordlenning** [comment]
Hi @rugk
Take a look at  "Multiple force closes on database requests" issue (816) closed.
Think it's the same..

**Comment by rugk** [comment]
Indeed this seems to be a dupe https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/816. So nice to see this issue was already resolved.

However - until the fixed version is released - does anyone have any idea about the "workaround"?

**Comment by f3ndot** [comment]
@rugk In lieu of a workaround, you can always compile from source and sideload onto your device

**Comment by rugk** [comment]
@f3ndot Well... I had a more simpler in mind (see my first post). (How) Can I get the API key from the Opencellid website somehow?

**Comment by f3ndot** [comment]
@rugk Go to http://opencellid.org/#action=database.requestForApiKey and set up an account. You'll receive your API key in am email

**Comment by Nordlenning** [comment]
@rugk You can also install AIMSICD WIP TEST RELEASE v0.1.39.1-alpha first, then Download API key with this version (it works). Then upgrade to version  WIP TEST RELEASE v0.1.41-alpha & the API key gets transfered to the upgraded version, that was my way. took me < 5 min.

**Comment by SecUpwN** [comment]
This is a `DUPLICATE` of the now resolved #816. Closed.

**Comment by rugk** [comment]
BTW why are your labels in capital letters? It really does not look nice/friendly when you're greeted with two big labels: `BUG`, `DUPLICATE`. It is nearly as if you had the labels `BUG!!` (red color), `DUPLICATE!!!` (grey) and `FUCK OFF!!11` (evil green color) there.
IMHO this discourages user/contributors as it really looks awful. The colored background should be enough to see it - you do not need caps lock there.

**Comment by SecUpwN** [comment]
>IMHO this discourages user/contributors as it really looks awful.

@rugk, you're the first one having a problem with this. would you contribute more if I change it? ;-)

**Comment by rugk** [comment]
Well... at least it would not look so bad. :grinning:

**Comment by SecUpwN** [comment]
>Well... at least it would not look so bad. :grinning:

@rugk, better now? Please help us to find more developers. Thanks.

**Comment by rugk** [comment]
Yeah, this looks more nicely... 

And I [tweeted](https://twitter.com/rugkme/status/714870006388023298) and [GNUSocialed](https://gnusocial.de/notice/7287198) about you. That's the only thing I can do right now.
BTW: You could also open a Twitter account or similar things to promote your app a bit. :wink:

**Comment by f3ndot** [comment]
The Twitter account is @AIMSICD

On Tue, Mar 29, 2016, 1:43 PM rugk <notifications@github.com> wrote:

> Yeah, this looks more nicely...
>
> And I tweeted <https://twitter.com/rugkme/status/714870006388023298> and
> GNUSocialed <https://gnusocial.de/notice/7287198> about you. That's the
> only thing I can do right now.
> BTW: You could also open a Twitter account or similar things to promote
> your app a bit. [image: :wink:]
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/822#issuecomment-203022451>
>
-- 
Justin Bull
PGP Fingerprint: E09D 38DE 8FB7 5745 2044 A0F4 1A2B DEAA 68FD B34C

**Comment by rugk** [comment]
> The Twitter account is @AIMSICD

Oh nice, did not know this. :smiley:

**Comment by SecUpwN** [comment]
>Oh nice, did not knew this.

@rugk, fully reading our `README` would help. ;-)

**Comment by rugk** [comment]
> fully reading our README would help. ;-)
Ah, yeah this small image there. :smiley:
