### ISSUE TITLE
Phone Type is being displayed instead of real Idle Status

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#826]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

When turning off `Toggle Attack Detection`, our app now switches into the proper `IDLE` mode (which was perviously fixed with #716). But instead of showing the proper `Status: Idle.` in the `NotificationDrawer`, only `Phone TypeGSM` is being shown. That is essentially wrong. Only this content shall be displayed:

```JAVA
 <string name="status_idle_description">Status: Idle.</string>
```

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

Uncheck `Toggle Attack Detection` and see that `Phone TypeGSM` appears instead of `Status: Idle.`

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

#716. Maybe @VladThodo is able to digg into fixing this. Would be kind if he did.

**Comment by VladThodo** [comment]
@SecUpwN I'm pretty busy those days but I will take a look at this as soon as I can ;)

**Comment by SecUpwN** [comment]
Thanks fworking to fix this, @larsgrefer! Is it intended to still show `Phone TypeGSM`? If so, would it be possible to align that somehhow for all languages to be viewed correctly like so: `Phone Type: GSM`?
