### ISSUE TITLE
OpenCellID API key is not immediately displayed

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#837]
**EDIT by SecUpwN:** @agilob, we have implemented `Issue Templates` for a reason! Please use it!

---

Description of Issue: After saving the new OCID API key, it does not show immediately in the field `OpenCellID API Key`. It is empty. Only after exiting the `Settings` and re-entering that field the key is shown. The way it should work is that it is immmediately shown when pressing that button after fetching it.

**Comment by mimi89999** [comment]
@agilob Exit AIMSICD. Reopen AIMSICD and check if the key has appeared.

**Comment by agilob** [comment]
Activity should listen for changes in shared preferences and update text field with the key, it has nothing to do with restarting application.

**Comment by Nordlenning** [comment]
The strange is that Key is downloaded & accepted since you can download OICD data without restarting the app, it's not displayed in the key requester until you restart the app.
OCID data gets downloaded.

**Comment by agilob** [comment]
> it's not displayed in the key requester until you restart the app.

No need to restart the app! Just restart preferences activity and the key is there.

**Comment by SecUpwN** [comment]
>No need to restart the app! Just restart preferences activity and the key is there.

So I guess the way it *should* work is that the key is shown immediately after it has been fetched?

**Comment by agilob** [comment]
Yes, that's the expected behaviour.

**Comment by Nordlenning** [comment]
This seems to be fixed in v0.1.43-alpha
OpenCellID API key is immediately displayed on my phone.

**Comment by agilob** [comment]
1. Uninstall AIMSICD
2. Install AIMSICD
3. Go to Settings
4. Request OCID
5. New bug, after successful request where API key was saved window with 'requesting key' is not closed...
6. Press back
7. Edit OCID API key
8. Field is empty

No, there are two bugs now there.

**Comment by SecUpwN** [comment]
@agilob, the main Issue I have with your bug reports is that you are _not_ using the bleeding edge work. Please make sure to compile our `development` branch before telling that a bug still exists. Thank you!

**Comment by agilob** [comment]
lol I'm not falling into this again.

**Comment by Nordlenning** [comment]
UnwiredLabs do not offer random  OCID API key so this could be closed
