### ISSUE TITLE
Operator name is empty on 2 sim cards I tested

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#845]
and two phones LG and Samsung, sim cards are from different networks.
Not sure if it's a bug, but the field should have something there. In 4 test cases at least one should have a value there.

**Comment by mimi89999** [comment]
Are you talking about dual sim devices? I can't reproduce this on my single SIM device: Samsung Galaxy S4 Mini (serranoltexx).

**Comment by agilob** [comment]
>Are you talking about dual sim devices? I can't reproduce this on my single SIM device: Samsung Galaxy S4 Mini (serranoltexx).

No

**Comment by mimi89999** [comment]
Are the devices running stock ROMS? My device is running CM13

**Comment by agilob** [comment]
Both have stock ROMs.

**Comment by mimi89999** [comment]
What operator?

**Comment by Nordlenning** [comment]
My Sony Xperia V CM Displays Correct Operator Name

**Comment by agilob** [comment]
3 and o2
http://www.controlf.net/iccid/ 23410 and 23420

**Comment by mimi89999** [comment]
It looks like this issue is ROM related.

**Comment by SecUpwN** [comment]
>It looks like this issue is ROM related.

Sure? I am experiencing this as well the whole time, might be related to #749.

**Comment by mimi89999** [comment]
Now I'm not so sure...

**Comment by SecUpwN** [comment]
>Now I'm not so sure...

How to find out?

**Comment by mimi89999** [comment]
Are devices running CM experiencing this problem?

**Comment by mimi89999** [comment]
If somebody could test the same SIM on a device running CM and another device running stock ROM...

**Comment by SecUpwN** [comment]
>Are devices running CM experiencing this problem?

Yes, I am. I'm running `AICP`, which is based on CM, see [Testing Devices](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Testing-Devices) and add your own.

**Comment by mimi89999** [comment]
Your ROM could (maybe for security reasons) block apps from accessing this data...

**Comment by agilob** [comment]
Closing because it's device specific apparently...
