### ISSUE TITLE
"Backup restore was successful", even if there was no backup...

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#847]
**EDIT by SecUpwN:** I guess what @agilob means is that `AIMSICD` needs to spit out an error instead.
@CellularPrivacy/database, please tackle this. Our app should notify: `Error: No backup found!`

**Comment by Nordlenning** [comment]
This Backup routine is gone in v0.1.43-alpha. Permanent or temporary ?

**Comment by agilob** [comment]
This backup was useless anyway and potentially damaging privacy.
