### ISSUE TITLE
[question] what is rej_cause in imported OCID data?

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#856]
and why is the number yellow?

**Comment by SecUpwN** [comment]
`rej_cause` = rejection cause. Does having a look at #250 answer your question?

**Comment by agilob** [comment]
>RED (small) = A BTS that is known (or unknown) to DBe_import where:
>rej_cause>0 or

Do  you know what rej_cause=3 mean? Why is known or unknown... one value can't mean two things.

**Comment by SecUpwN** [comment]
>Why is known or unknown... one value can't mean two things.

>  * ***rej_cause>0***   or
>  * `Samples: [0,-1]`   or
>  * A5/x **<** A5/3     
>  * **or** A BTS that is new or unknown to **DBe_import**.

As you can see, it can even mean **four** different things.

>Do you know what rej_cause=3 mean?

The way I see it,it means that `A5/x < A5/3`.

**Comment by larsgrefer** [comment]
the value is set here:

```java
        //=============================================================
        //===  UPDATE "rej_cause" in BTS data (DBe_import)
        //=============================================================

        // =========== isGPSexact ===========
        // Increase rej_cause, when:  the GPS position of the BTS is not exact:
        // NOTE:  In OCID: "changeable"=1 ==> isGPSexact=0
        sqlQuery = "UPDATE DBe_import SET rej_cause = rej_cause + 3 WHERE isGPSexact=0";
        mDb.execSQL(sqlQuery);

        // =========== avg_range ===========
        // Increase rej_cause, when:  the average range is < a minimum GPS precision
        sqlQuery = "UPDATE DBe_import SET rej_cause = rej_cause + 3 WHERE avg_range < " + min_gps_precision;
        mDb.execSQL(sqlQuery);

        // =========== time_first ===========
        // Increase rej_cause, when:  the time first seen is less than a number of days.
        // TODO: We need to convert tf_settings to seconds since epoch/unix time...
        //      int tf_settings = current_time[s] - (3600 * 24 * tf_settings) ???
        //sqlQuery = "UPDATE DBe_import SET rej_cause = rej_cause + 1 WHERE time_first < " + tf_settings;
        //mDb.execSQL(sqlQuery);
```
>https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/6125b1db3aec844f545bc1911ab53381e4e55494/AIMSICD/src/main/java/com/secupwn/aimsicd/adapters/AIMSICDDbAdapter.java#L1030-1050

The value is never used in the current code (except for displaying the database viewer)

**Comment by agilob** [comment]
thanks
