### ISSUE TITLE
[Info] Github Research Survey Participation Request about AIMSICD

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#860]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

--- I got this in my mailbox today, someone is finding AIMSCID interesting :)

Dear Nordlenningen,

My name is Pierce MacMillan and I am an Information Systems graduate student researcher at the University of Maryland, Baltimore County.  My team and I are researching static analysis tool use among Github Android app developers, and we have selected your app, Android-IMSI-Catcher-Detector, for our research project.  We are specifically studying if static analysis tools are being used by developers, and if not, what is hindering their popularity.  As you may be aware, static analysis testing tools are automated source code scanners that check for potential faults and bad coding practices.  Examples of such static analysis tools for Java code are Findbugs, Checkstyle, PMD. 

We would greatly appreciate your help in furthering our research!  If you could please take two minutes to respond to the our survey, you would help us tremendously and further research into automated software testing tools, so that they might be improved and make software testing easier for everyone.
 
xttps://subtle-breaker-720.appspot.com/Redirect?ukey=1vl9Z-1SdkLzmwQsCrQyKrz_h-ZbOEvc78lhEne-ETco-395500385&key=YAMMID-97516292&link=xttp://goo.gl/forms/rrZVfMnXH4)

Thanks in advance for your assistance.

Sincerely,
Pierce MacMillan  

Note: Changed h - x in link to avoid accidental klick.
#### Reproduction

>Please tell us the detailed steps on how to reproduce your Issue here.

--- 

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by SecUpwN** [comment]
@Nordlenning, is that your survey? I have received this via E-mail as well. Surveys do not contribute to this project and are not an "Issue" either. Please make sure to use our Issue tracker for real Issues only.
