### ISSUE TITLE
Gradle sync failed: CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by hanks9910** [CellularPrivacy/Android-IMSI-Catcher-Detector#861]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [X] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [X] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [X] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen): 03.04.2016 - WIP-Release v0.1.42-alpha
* Phone and ROM running *current* release: N/A
* Link to logfile without identifyable data: N/A

Hello,

I cloned the latest project and opened it with Android Studio 1.5, but got below Gradle sync error
"Error:(26, 0) CreateProcess error=2, The system cannot find the file specified"

while line #26 of root build.gradle is
   apply plugin: 'io.freefair.git-version'

Here is screenshot, can you suggest how to resolve this issue
![screen](https://cloud.githubusercontent.com/assets/3981885/14375977/7d5a9520-fd1a-11e5-8411-db3b56924b0d.jpg)

Thanks.

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.
1. clone the project
2.  open it in Android Studio 1.5
3. grade sync

---

**Comment by larsgrefer** [comment]
Try opening the **Terminal** window in AndroidStudio and run `gradlew build`

**Comment by hanks9910** [comment]
thanks, and it is resolved after configure git path and run gradlew build again

**Comment by litesam** [comment]
@hanks9910 how did you configured the git path?

**Comment by larbikhounti** [comment]
how did you configured the git path?

**Comment by avinashofb** [comment]
Just use this command -> where is git
Use that path in your Android Studio -> Open Android Studio and go to: Menu Settings → Version Control → Git
