### ISSUE TITLE
AT command interface doesn't execute anything

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#864]
I tried to execute command `AT+CRSM=176,28589,0,0,3` and nothing happens when I press execute.

I tried also `AT+CRSM=176,28423,0,0,9` and `AT+CREG?` and `AT+CRSM=176,28542,0,0,11`

No effect.

**Comment by SecUpwN** [comment]
Closing this as `duplicate` of #754.
