### ISSUE TITLE
Inconsistent spelling: Neighbouring vs. Neighboring

### ISSUE THREAD

**Issue by SecUpwN** [CellularPrivacy/Android-IMSI-Catcher-Detector#865]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [X] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [X] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [X] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

While fixing #848, it came to my attention that our code and documentation has been invaded by a creepy spelling bug: We currently use both `neighbouring` *and* `neighboring` on our repository. This inevitably leads to coding and translation problems (therefore our `development` branch is currently broken). We need to decide on this ASAP so that everyone knows which spelling to use in the future.

* I also found this note in `CellTracker.java`:

```
[  ] Attention to the spelling of "neighbor" (USA) Vs. "neighbour" (Eng world)
```
---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

This is how the Android Developer Resource is spelling it: `Neighboring`. Shall we go with that?

https://developer.android.com/reference/android/telephony/NeighboringCellInfo.html

---

@larsgrefer, you also use `neighbour` in your diagram. I would like to go with the most plausible solution here. Do you agree that we should be using `neighboring` everywhere from now on? If so, please send me an updated version of your diagram via E-Mail and I will fix our whole codebase today! Thank you.

**Comment by agilob** [comment]
neighboring - US English
neighbouring - UK English

**Comment by larsgrefer** [comment]
@SecUpwN Yes, let's use Neighbor
