### ISSUE TITLE
Cannot upgrade to v0.1.43-alpha

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#869]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

Sony experia V lt25i CM lollipop. 
AIMSCID WIP TEST RELEASE v0.1.43-alpha Don't Upgrade
you have to do a clean install (removing 0.1.42 first)..

Downloaded from Github.
#### Reproduction

Try to upgrade 

---
#### References

Log  https://defuse.ca/b/SSo3BZB8SaptaogHwyULTs

---
#### Screenshots

> If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by SecUpwN** [comment]
@larsgrefer, I suspect this to be a temporary bug due to the new database. Is that correct?

**Comment by larsgrefer** [comment]
@SecUpwN Not sure yet

@Nordlenning Was your previously installed 0.1.42 also downloaded from github?

**Comment by Nordlenning** [comment]
Yes, I download all from github or compile from source, but when I run into this I removed 0.1.42 first & installed 0.1.42 from f-droid & tried that way, same result.

**Comment by mimi89999** [comment]
@Nordlenning What was the error message when you were installing the new version?

**Comment by Nordlenning** [comment]
Could not install (when upgrading) No error from clean install..
Think it complained about some signature difference..

**Comment by larsgrefer** [comment]
@Nordlenning You can only upgrade from one github-build to another github-build or from one f-droid build to another f-droid build.

**Comment by Nordlenning** [comment]
That may explain this, I was using 0.1.42 build from source after some fix made by @mimi89999.
So I close this if nobody else is having issues with this. Thanks @larsgrefer  I will remember that, good information given.

**Comment by larsgrefer** [comment]
Every android app (apk file) is digitally signed by the one who build it. When installing an app update android checks if the new apk was signed with the same key, the old one was signed with.

Unfortunately the f-droid builds are signed with another key than our github builds

**Comment by Nordlenning** [comment]
Yes I see,  that does mean that you cannot cross-install between  XDA, github, F-droid, & they are signed with different keys ? You have to stick with the same source you downloaded from. 
So when I compile from source i will run into this every time I try installing new github apk.
So if I compile from source every time I wont have this issue.

**Comment by SecUpwN** [comment]
@Nordlenning, as a rule of thumb: The GitHub release, Aptoide and XDA Labs are essentially the same build, which I personally upload. The one from F-Droid is an independent build directly crafted from our GitHub repo and signed by them. Means: You can cross-update from all of the other sources, except the one from F-Droid. Enjoy! ;-)
