### ISSUE TITLE
Crash after OCID DB is downloaded v0.1.43-alpha

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#870]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**
#### Overview

> Please add a short and easy to understand description of the Issue you've experienced here.
> Sony experia V lt25i CM lollipop.
> AIMSICD WIP TEST RELEASE v0.1.43-alpha

Redakted:
AIMSICD crash whatever you do in db view if you minimize / reopen it.
Made 20 crashes in 20 minutes.. All imported ocid cells having PSC 666 can be the clue...

See also issue 831
#### Reproduction

Same as above
#### Screenshots

> If you experienced visual glitches, please add a screenshot without metadata here.
> ![screenshot from 2016-05-02 02 07 56](https://cloud.githubusercontent.com/assets/17292772/14945351/08869cf6-0fff-11e6-9167-d40a7926ac93.png)

**Comment by mimi89999** [comment]
Have you uninstalled and reinstalled or just updated AIMSICD?

**Comment by Nordlenning** [comment]
I have clean installed 0.1.43 downloaded from github.

ADDED:
1 way to make it crash is: Go into DB-view push one or 2 of the tabs, minimize AIMSICD, maximize AIMSICD again, push one of the tabs in DB-view again = Crash (or to be more precise Restarting) 
Done this many times now, no problem to make it "restart".. 

FATAL EXCEPTION: main
Process: com.SecUpwN.AIMSICD, PID: 29476
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
Log: https://defuse.ca/b/aEVfN2U2sKEk2OUIXTjJIy

@SecUpwN you may change the title on this, since this is mostly the same as 831, only with the new Version. No point in keeping same issues in 2 treads. This has probably nothing to do with OCID download.

**Comment by Nordlenning** [comment]
The 2 crash will be harder for the pro's to crack & will probably demand some serious work. This is the bad one.

This crash is a "delayed" crash & appears some time after the actual crash is made.
With delayed I mean that the crash may appear (usually does) long time after the crash actually has happen.

I discovered this several times when putting my phone on the table & could see it crash after 10sec or more just laying on my table, without touching the phone. This is the same crash-behavior I discovered in 0.1.42.

Several times I could see AIMSICD crash in the background, just flashing me the usual start up msg, so AIMSICD rebooted itself in the background. That's one of the reasons AIMSICD crash in different places (screenshots).
So crash may be reported in places that is not related to the crash. Making this difficult to pinpoint.

The only way to track this may be to watch logcat live on PC & Zoom inn/out & move around in Map-view. You will see that AIMSICD starts to get slooow in map view & later on crash, seconds/minutes later, so if you leave Map-view AIMSICD may crash in other places.

This crash ONLY happens if you have been maneuvering in MAP view.
I think this must be logged by the pro's who knows what they should look for in live log, otherwise it will be a long log for others to edit.

This crash is definitively related to Map-view, that's all I can say.. I would say buffer,memory trouble, something gets filled up until crash.
Took AIMSICD v 0.1.43 out for a ride in my car today watching Map, 5min later it crash on my dashboard. Hope this may be of any help.

**Comment by Nordlenning** [comment]
AIMSICD Crash Downloading OCID DB from MAP view.

D/RealmHelper(7362): CheckDBe() Attempting to delete bad import data from Imports database...
D/AndroidRuntime(7362): Shutting down VM
E/AndroidRuntime(7362): FATAL EXCEPTION: main
E/AndroidRuntime(7362): Process: com.SecUpwN.AIMSICD, PID: 7362
E/AndroidRuntime(7362): java.lang.IllegalArgumentException: Field 'cell' does not exist.
Log https://defuse.ca/b/mkbSlYP1xfk5I3l1Zm4qLx

AIMSICD Crash Downloading OCID DB from Main Menu
Log https://defuse.ca/b/MVTdQcR43t16gH14C4aX3N

**Comment by Nordlenning** [comment]
AIMSICD WIP TEST RELEASE v0.1.43-alpha compiled from source 010616

06-02 00:44:36.491: E/AndroidRuntime(12893): FATAL EXCEPTION: main
06-02 00:44:36.491: E/AndroidRuntime(12893): Process: com.SecUpwN.AIMSICD, PID: 12893
06-02 00:44:36.491: E/AndroidRuntime(12893): java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

06-02 01:42:49.770: E/AndroidRuntime(16818): FATAL EXCEPTION: main
06-02 01:42:49.770: E/AndroidRuntime(16818): Process: com.SecUpwN.AIMSICD, PID: 16818
06-02 01:42:49.770: E/AndroidRuntime(16818): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
06-02 01:42:49.770: E/AndroidRuntime(16818):    at com.secupwn.aimsicd.utils.RealmHelper$3.execute(RealmHelper.java:453)

https://defuse.ca/b/Gu6hpTBRFaifIHPnV4MrB6
