### ISSUE TITLE
Job offer from osmocom

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#872]
http://laforge.gnumonks.org/blog/20160502-osmocom-sysmocom-jobs/

maybe someone watchng this repo will be interested.

**Comment by agilob** [comment]
Just wanted to let you know guys. Can be closed now.

**Comment by ghost** [comment]
That is an amazing opportunity for a skilled programmer and the guys at osmocom are legends. Very advanced programming knowledge needed tho to get involved there.

**Comment by SecUpwN** [comment]
Thanks for opening this @agilob. Indeed very interesting, but also very sad to see that none of the developers of @sysmocom (respectively also @laf0rge) has joined our efforts so far. I mentioned them just to make sure they noticed us. If they join us, I'll offer to tweet about their job offer with our official Twitter account. Closing this as solved now.

**Comment by laf0rge** [comment]
@SecUpwN I think I have dedicated more than my fair share in terms of creating FOSS GSM software during the past 8 years. I am hacking pretty much every hour awake, and despite that all existing projects get by far insufficient attention. Asking me to get involved in even more projects is out of the question.

**Comment by ghost** [comment]
@laf0rge The work you guys have done to date is ground breaking and wouldn't have happened for another 10 years if you guys hadn't showed us what is possible.  Everything that was implemented on this project was from the knowledge that was shared from your hacking so your contributing to the community and lots of projects in that sense.

Great respect for you guys and hope ye bring more vulnerabilities to our attention.

Regards
