### ISSUE TITLE
Cannot install 01.43.alpha on Samsung sgh-t769

### ISSUE THREAD

**Issue by sglanger** [CellularPrivacy/Android-IMSI-Catcher-Detector#877]
When I follow my usual procedure of downloading the apk and allowing the unknown sources to install, i tried the Package Installer and get "Parse Error: problem parsing the package" This is on a stock, unrooted, Android 2.3.6

**Comment by SecUpwN** [comment]
Good evening, I'm sorry to hear this. Please verify that the downloaded APK matches the listed MD5 sum.

**Comment by larsgrefer** [comment]
The app requries at least Android 4.1

(the minSdk is set to 16)

**Comment by sglanger** [comment]
it does

________________________________

**Comment by sglanger** [comment]
I wondered about that. It might be nice if it said that here

https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Requirements
