### ISSUE TITLE
Unwired Labs would like to help this project with our Cell Database

### ISSUE THREAD

**Issue by gopi-ar** [CellularPrivacy/Android-IMSI-Catcher-Detector#881]
Hi there,

We run Unwired Labs, a leading Cell Tower & WiFi geolocation service. Some of our customers are in the business of detecting 'bad' cell towers and we came across your project recently.

We're open to sharing our data about cell-tower's locations to help make this detection even better.

Let me know how you'd like to explore this.

Cheers,
Gopi

**Comment by He3556** [comment]
Hello Gopi

That is a great offer! This data would help us a lot. Maybe we can email and talk about the details?
 info@dm-development.de 
 i will forward it to the project organizer Secupwd. 

Looking forward to your reply, 
cheers marcus

**Comment by gopi-ar** [comment]
Sure thing, will reach out on email.

**Comment by TPS** [comment]
Cont'd further in #891, I believe.
