### ISSUE TITLE
Many cells near home

### ISSUE THREAD

**Issue by OliverElfe** [CellularPrivacy/Android-IMSI-Catcher-Detector#882]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [_] *_I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [_] *_I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [_] *_I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

I see two or three cells near home but there's no cell so far !
I have noted the cells ID, LAC... and tried to locate them on internet but I did not find them.
- `AIMSICD` version (see the `About` screen): 0.1.43
- Phone and ROM running _current_ release: Archos Hélium 45b (AC45BHE) Android 4.4.4
- Link to logfile without identifyable data:

------------ beginning of /dev/log/main
D/ActivityThread( 8722): handleBindApplication:com.SecUpwN.AIMSICD
D/ActivityThread( 8722): setTargetHeapUtilization:0.75
D/ActivityThread( 8722): setTargetHeapMinFree:524288
D/Injector( 8722): Injection of com.secupwn.aimsicd.AndroidIMSICatcherDetector@41cb5f00 took 31ms
D/dalvikvm( 8722): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm( 8722): VFY: unable to resolve static field 74 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm( 8722): VFY: replacing opcode 0x62 at 0x0039
D/dalvikvm( 8722): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
I/dalvikvm( 8722): DexOpt: unable to optimize static field ref 0x004a at 0x3e in Lio/realm/internal/android/ReLinker;.unpackLibrary
D/dalvikvm( 8722): Trying to load lib /mnt/asec/com.SecUpwN.AIMSICD-1/lib/librealm-jni.so 0x41cb4798
D/dalvikvm( 8722): Added shared lib /mnt/asec/com.SecUpwN.AIMSICD-1/lib/librealm-jni.so 0x41cb4798
I/dalvikvm( 8722): Could not find method android.content.Context.getDrawable, referenced from method io.freefair.android.injection.injector.AndroidResourceInjector.injectResources
W/dalvikvm( 8722): VFY: unable to resolve virtual method 178: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 8722): VFY: replacing opcode 0x6e at 0x016f
D/Injector( 8722): Injection of com.secupwn.aimsicd.service.AimsicdService@41cf15d8 took 10ms
D/dalvikvm( 8722): GC_CONCURRENT freed 302K, 13% free 3019K/3444K, paused 1ms+9ms, total 28ms
E/RilExecutor( 8722): Samsung Multiclient RIL not available: gsm.version.ril-impl = Qualcomm RIL 1.0
I/AimsicdService( 8722): Service launched successfully.
I/CellTracker( 8722): CheckForNeighborCount()
D/CellTracker( 8722): NC list not supported by AOS on this device. Nothing to do.
D/CellTracker( 8722): : Setting nc_list_present to: false
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 18522205 due to device movement. Waiting for 29717 ms.
D/roidIMSICatcherDetector( 8722): Loading default data successful
I/CellTracker( 8722): CheckForNeighborCount()
D/CellTracker( 8722): NC list not supported by AOS on this device. Nothing to do.
D/CellTracker( 8722): : Setting nc_list_present to: false
I/CellTracker( 8722): CheckForNeighborCount()
D/CellTracker( 8722): NC list not supported by AOS on this device. Nothing to do.
D/CellTracker( 8722): : Setting nc_list_present to: false
D/dalvikvm( 8722): GC_CONCURRENT freed 304K, 12% free 3138K/3540K, paused 2ms+5ms, total 17ms
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 25861 ms.
I/CellTracker( 8722): CheckForNeighborCount()
D/CellTracker( 8722): NC list not supported by AOS on this device. Nothing to do.
D/CellTracker( 8722): : Setting nc_list_present to: false
W/dalvikvm( 8722): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm( 8722): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm( 8722): VFY: unable to resolve interface method 7679: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm( 8722): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 8722): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm( 8722): VFY: unable to resolve interface method 7683: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm( 8722): VFY: replacing opcode 0x72 at 0x0002
D/Injector( 8722): Injection of com.secupwn.aimsicd.ui.activities.AboutActivity@41cf2460 took 41ms
D/dalvikvm( 8722): GC_FOR_ALLOC freed 212K, 9% free 3295K/3584K, paused 12ms, total 12ms
I/dalvikvm-heap( 8722): Grow heap (frag case) to 4.394MB for 635812-byte allocation
D/dalvikvm( 8722): GC_CONCURRENT freed 42K, 8% free 3874K/4208K, paused 2ms+2ms, total 29ms
I/Adreno-EGL( 8722): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL( 8722): OpenGL ES Shader Compiler Version: E031.24.02.07
I/Adreno-EGL( 8722): Build Date: 11/26/14 Wed
I/Adreno-EGL( 8722): Local Branch: 
I/Adreno-EGL( 8722): Remote Branch: 
I/Adreno-EGL( 8722): Local Patches: 
I/Adreno-EGL( 8722): Reconstruct Branch: 
D/OpenGLRenderer( 8722): Enabling debug mode 0
I/Timeline( 8722): Timeline: Activity_idle id: android.os.BinderProxy@41d18c70 time:103407779
I/CellTracker( 8722): CheckForNeighborCount()
D/CellTracker( 8722): NC list not supported by AOS on this device. Nothing to do.
D/CellTracker( 8722): : Setting nc_list_present to: false
D/dalvikvm( 8722): GC_CONCURRENT freed 829K, 21% free 3438K/4344K, paused 2ms+2ms, total 12ms
I/LocationTracker( 8722): Last known location (45.54731°, 4.48904°) = (0.7949505249265385 rad, 0.07834852825372626 rad)
D/Injector( 8722): Injection of com.secupwn.aimsicd.ui.activities.MainActivity@41cc4818 took 94ms
D/dalvikvm( 8722): GC_FOR_ALLOC freed 111K, 19% free 3525K/4344K, paused 10ms, total 10ms
I/dalvikvm-heap( 8722): Grow heap (frag case) to 4.619MB for 635812-byte allocation
D/dalvikvm( 8722): GC_CONCURRENT freed 12K, 17% free 4134K/4968K, paused 2ms+1ms, total 12ms
D/Injector( 8722): Injection of com.squareup.okhttp.OkHttpClient@41cecde0 took 24ms
D/Injector( 8722): Injection of DeviceFragment{41cb5818 #0 id=0x7f0d007e} took 44ms
D/roidIMSICatcherDetector( 8722): BaseTask attach:com.secupwn.aimsicd.ui.activities.MainActivity
D/MainActivity( 8722): StatusWatcher starting watching
D/dalvikvm( 8722): GC_CONCURRENT freed 802K, 25% free 3747K/4968K, paused 3ms+3ms, total 22ms
I/AimsicdService( 8722): Sms Detection Thread Started
I/SmsDetector( 8722): SMS detection started
I/MainActivity( 8722): SMS Detection Thread Started
I/Timeline( 8722): Timeline: Activity_idle id: android.os.BinderProxy@41ced3e0 time:103410406
D/dalvikvm( 8722): GC_CONCURRENT freed 163K, 18% free 4096K/4968K, paused 21ms+5ms, total 58ms
D/dalvikvm( 8722): WAIT_FOR_CONCURRENT_GC blocked 1ms
D/dalvikvm( 8722): WAIT_FOR_CONCURRENT_GC blocked 14ms
D/dalvikvm( 8722): GC_CONCURRENT freed 81K, 10% free 4508K/4968K, paused 2ms+5ms, total 26ms
D/dalvikvm( 8722): GC_CONCURRENT freed 70K, 3% free 4936K/5080K, paused 2ms+4ms, total 20ms
D/dalvikvm( 8722): GC_CONCURRENT freed 167K, 5% free 5343K/5584K, paused 3ms+3ms, total 27ms
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 26358 ms.
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 26266 ms.
I/RealmHelper( 8722): BTS updated: CID=31400027 LAC=3420
I/RealmHelper( 8722): DBi_measure updated bts_id=31400027
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 24307 ms.
D/dalvikvm( 8722): GC_CONCURRENT freed 550K, 11% free 5506K/6132K, paused 4ms+9ms, total 40ms
I/dalvikvm( 8722): Could not find method android.support.v7.widget.ListPopupWindow$DropDownListView.drawableHotspotChanged, referenced from method android.support.v7.widget.ListPopupWindow$DropDownListView.setPressedItem
W/dalvikvm( 8722): VFY: unable to resolve virtual method 6420: Landroid/support/v7/widget/ListPopupWindow$DropDownListView;.drawableHotspotChanged (FF)V
D/dalvikvm( 8722): VFY: replacing opcode 0x6e at 0x000a
I/dalvikvm( 8722): Could not find method android.view.View.drawableHotspotChanged, referenced from method android.support.v7.widget.ListPopupWindow$DropDownListView.setPressedItem
W/dalvikvm( 8722): VFY: unable to resolve virtual method 7418: Landroid/view/View;.drawableHotspotChanged (FF)V
D/dalvikvm( 8722): VFY: replacing opcode 0x6e at 0x004a
D/dalvikvm( 8722): GC_FOR_ALLOC freed 37K, 10% free 5608K/6212K, paused 14ms, total 14ms
I/dalvikvm-heap( 8722): Grow heap (frag case) to 6.653MB for 635812-byte allocation
D/dalvikvm( 8722): GC_FOR_ALLOC freed 9K, 9% free 6251K/6836K, paused 23ms, total 24ms
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 23413 ms.
I/Timeline( 8722): Timeline: Activity_launch_request id:com.SecUpwN.AIMSICD time:103418539
W/InputEventReceiver( 8722): Attempted to finish an input event but the input event receiver has already been disposed.
D/MainActivity( 8722): StatusWatcher stopped watching
D/Injector( 8722): Injection of com.secupwn.aimsicd.ui.activities.DebugLogs@41f62880 took 111ms
D/DebugLogs( 8722): StatusWatcher starting watching
I/Timeline( 8722): Timeline: Activity_idle id: android.os.BinderProxy@41f61ef8 time:103421395
D/roidIMSICatcherDetector( 8722): BaseTask detach:com.secupwn.aimsicd.ui.activities.MainActivity
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 17377 ms.
D/dalvikvm( 8722): GC_CONCURRENT freed 1388K, 20% free 5876K/7340K, paused 5ms+4ms, total 67ms
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 14308 ms.
D/dalvikvm( 8722): GC_CONCURRENT freed 992K, 21% free 5865K/7340K, paused 3ms+4ms, total 51ms
I/RealmHelper( 8722): BTS updated: CID=31400027 LAC=3420
I/RealmHelper( 8722): DBi_measure updated bts_id=31400027
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 11075 ms.
D/dalvikvm( 8722): GC_CONCURRENT freed 763K, 18% free 6051K/7340K, paused 4ms+4ms, total 30ms
I/LocationTracker( 8722): Last known location (xx.xxxxx°, x.xxxxx°) = (0.xxxxxxxxxxxxxxxxxx rad, 0.xxxxxxxxxxxxxxxxxxx rad)
I/SignalStrengthTracker( 8722): Ignored signal sample for CID: 31400027 due to device movement. Waiting for 28736 ms.
#### Reproduction

> no special steps

---
#### References

> If your Issue is related to any other existing Issues or pull requests, please link them here.

---
#### Screenshots

https://goo.gl/photos/g68x8stF4PF4kJXX7

**Comment by Coehill** [comment]
Have you tried uploading BTS data?  For me, what worked was using one of the [recommended apps from the OpenCellID](http://wiki.opencellid.org/wiki/Data_sources) wiki to record the data myself.  [inViu OpenCellID ](https://www.enaikoon.com/en/apps/plugins/opencellid/)worked well for me on Andoid.

**Comment by Nordlenning** [comment]
This could be closed, likely referring to 471 & related issues
