### ISSUE TITLE
Crash after OCID DB is downloaded

### ISSUE THREAD

**Issue by Osteri** [CellularPrivacy/Android-IMSI-Catcher-Detector#888]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

> The generated getter function _setRejCause_ expects a valid Integer object. The object should be coverted in to a primitive int, which does not happen, when the converted Integer value is null (and not a valid Integer): _java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference_

This is not a duplicate of [https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/870](url), since it solves a different issue.

**I have already made a fix for this and will make a pull request later. I created this issue just to trace this specific issue.**
- `AIMSICD` version (see the `About` screen): latest development branch; **v0.1.43-alpha-SNAPSHOT-normal**
- Phone and ROM running _current_ release: **omnirom 6.0.1**
- Link to logfile without identifyable data: 

```
06-02 01:42:49.770: E/AndroidRuntime(16818): FATAL EXCEPTION: main
06-02 01:42:49.770: E/AndroidRuntime(16818): Process: com.SecUpwN.AIMSICD, PID: 16818
06-02 01:42:49.770: E/AndroidRuntime(16818): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
06-02 01:42:49.770: E/AndroidRuntime(16818): at com.secupwn.aimsicd.utils.RealmHelper$3.execute(RealmHelper.java:453)
```

---
#### Reproduction

> Clean installation; try to download OCID data, program forcefully closes (unhandled exception).

---
#### References

> This problem is also referenced in @Nordlenning's comment: https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/870#issuecomment-223381051

Note: there are 2 separate fatal exceptions at @Nordlenning's log output, this ticket is only created for the other exception.

---

**Comment by sciamano** [comment]
I see a crash too when trying to download the database. I did following: 1) clear all app data, 2) get ID-key, 3) start the DB download. At step 3 the app always crashes :( 

Here is few lines from log-file, which I think are relevant

```
D/Injector(19087): Injection of com.secupwn.aimsicd.utils.RequestTask@6c3b9f took 6ms
D/roidIMSICatcherDetector(19087): BaseTask addTask activity:com.secupwn.aimsicd.ui.activities.MainActivity
I/RequestTask(19087): DBE_DOWNLOAD_REQUEST write to: /storage/emulated/0/Android/data/com.SecUpwN.AIMSICD/files/OpenCellID/opencell
id.csv
I/SignalStrengthTracker(19087): Ignored signal sample for CID: 5634267 due to device movement. Waiting for 20553 ms.
D/RequestTask(19087): doInBackground DBE_DOWNLOAD_REQUEST total not returned!
I/RealmHelper(19087): UpdateOpenCellID: OCID CSV size (lines): 621
D/RealmHelper(19087): PopulateDBeImport(): inserted 621 cells.
D/RealmHelper(19087): CheckDBe() Attempting to delete bad import data from Imports database...
D/AndroidRuntime(19087): Shutting down VM
I/Process (19087): Sending signal. PID: 19087 SIG: 9

```

after crash, the file `/storage/emulated/0/Android/data/com.SecUpwN.AIMSICD/files/OpenCellID/opencell
id.csv` exists and contains some csv data
