### ISSUE TITLE
Generic question

### ISSUE THREAD

**Issue by ghost** [CellularPrivacy/Android-IMSI-Catcher-Detector#896]
Hello. Unfortunately i'm not very skilled in the field and then I would like to ask you something (I hope it is not a stupid question): 

if the cell use only the WiFi, without access to other networks, this app is not necessary, right? 

let me explain: I have 2 phones. the first use it to work and has a SIM card, the second is to private, and use only the WiFi and with the flight mode always active. 

For the second, the app doesn't need because, apart the WiFi, the phone is "isolated" and don't use the cell networks, right ??

**Comment by webcoderz** [comment]
You can intercept wifi transactions also.Perhaps not with this app
presently but with something called a pineapple or a rogue access point.

**Comment by He3556** [comment]
yes, this app is not necessary for the "wifi phone". How are you forwarding the incomming calls from phone1 (with sim card) to phone2 (wifi)? 
Is there finally a App for it? 
I was looking for one 2 years ago but didn't find anything that could forward to VoIP/SIP. Only Routers with sim card slot can do it, as far as i know.

**Comment by webcoderz** [comment]
Signal might

**Comment by ghost** [comment]
@He3556
1) The 2 phones not communicate with each other. The first is that "official" and detectable by the State, the second is to "unofficial" and invisible.

2) The only app (which I feel decent and don't require a SIM number), which allows you to make this kind of service is called "Secure Call" (developer: "eBilge"). But there is a problem: Play Store, close-source and only 1 week free trial. Once over you must necessarily make a subscription, if you want to use it.

3) the router with SIM shall be binding on "closed" ROM .. but not on CyanogenMod. In fact (the second mobile is a Galaxy S4 with CM) allows me to create a hotspot without SIM, and then without Internet access
