### ISSUE TITLE
Downloading BTS Data occurs to a reproducible crash

### ISSUE THREAD

**Issue by ghost** [CellularPrivacy/Android-IMSI-Catcher-Detector#899]
> Thank you for your feedback! Please add below details so that we can help you a bit faster.

---
#### Agreements

> Please check these boxes to ensure you've actually read and understood these important rules!
- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---
#### Overview

> Please add a short and easy to understand description of the Issue you've experienced here.
- `AIMSICD` version (see the `About` screen): 0.1.43
- Phone and ROM running _current_ release: lg v10. H960a. Rom v20b
- Link to logfile without identifyable data:
```
  09-17 12:33:45.739 E/AndroidRuntime(23182): FATAL EXCEPTION: main
  09-17 12:33:45.739 E/AndroidRuntime(23182): Process: com.SecUpwN.AIMSICD, PID: 23182
  09-17 12:33:45.739 E/AndroidRuntime(23182): java.lang.IllegalArgumentException: Field 'cell' does not exist.
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at io.realm.RealmObjectSchema.getColumnIndices(RealmObjectSchema.java:574)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at io.realm.RealmQuery.lessThan(RealmQuery.java:734)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at com.secupwn.aimsicd.utils.RealmHelper$3.execute(RealmHelper.java:422)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at io.realm.Realm.executeTransaction(Realm.java:1109)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:301)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:81)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.os.AsyncTask.finish(AsyncTask.java:651)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.os.AsyncTask.access$500(AsyncTask.java:180)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.os.Handler.dispatchMessage(Handler.java:102)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.os.Looper.loop(Looper.java:148)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at android.app.ActivityThread.main(ActivityThread.java:5551)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at java.lang.reflect.Method.invoke(Native Method)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
  09-17 12:33:45.739 E/AndroidRuntime(23182):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
  09-17 12:33:45.746 W/ActivityManager(1590):   Force finishing activity com.SecUpwN.AIMSICD/com.secupwn.aimsicd.ui.activities.MainActivity
```
#### Reproduction

> Please tell us the detailed steps on how to reproduce your Issue here.
> I have asked for an api key through settings.
> ## Then every time I select to download BTS Data from the menu, the app crashes
#### References

> If your Issue is related to any other existing Issues or pull requests, please link them here.

---
#### Screenshots

> If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by Nordlenning** [comment]
Hi @mpqo, This was fixed with commit  7142c6e  "fix realm query " so this is invalid..
You may test it with my latest test apk here >> Removed

**Comment by ghost** [comment]
![screenshot_2016-09-21-16-47-33](https://cloud.githubusercontent.com/assets/3320229/18715961/5d06f6ea-801b-11e6-9e2b-95db6debaa6f.png)

Confirming as fixed :)

**Comment by johnbradypresents** [comment]
I am still having this issue

**Comment by darkerego** [comment]
It's been fixed for me, did you pull the latest source?

**Comment by Rbagman** [comment]
Same here, posted before but have since installed Xposed Framework Module: Scoop
Stack Trace:

```
java.lang.IllegalArgumentException: Field 'cell' does not exist.
	at io.realm.RealmObjectSchema.getColumnIndices(RealmObjectSchema.java:574)
	at io.realm.RealmQuery.lessThan(RealmQuery.java:734)
	at com.secupwn.aimsicd.utils.RealmHelper$3.execute(RealmHelper.java:422)
	at io.realm.Realm.executeTransaction(Realm.java:1109)
	at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:317)
	at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:81)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```
