### ISSUE TITLE
Support other network type

### ISSUE THREAD

**Issue by ghost** [CellularPrivacy/Android-IMSI-Catcher-Detector#908]
I read your FAQ but I can't found my answer, so I ask this:

Is AICD app detect *only* GSM network?
GSM is older than 2G. Many area in the worldwide use 3G, and developed countries use 4G/LTE.

btw I always use Orbot when I use mobile network(3G), and I don't use SMS.

**Comment by TPS** [comment]
Duplicates #216; #489 & #442 track progress for CDMA & LTE, respectively.
