### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by punkifier** [CellularPrivacy/Android-IMSI-Catcher-Detector#914]
Android studio installed in C:\
While Git installed in C:\Program Files\Git

I have look over the forums and many people with the same problem has been solved. I followed every single one of them and I still can't seem to sync. Help !

![problem](https://cloud.githubusercontent.com/assets/25942684/23249411/325ed2bc-f9df-11e6-9153-0fad6994cbd6.PNG)

![problem2](https://cloud.githubusercontent.com/assets/25942684/23249612/37352dda-f9e0-11e6-80f3-081635e0db3d.PNG)

**Comment by larsgrefer** [comment]
Hi @punkifier 

- Have you restarted *AndroidStudio* after changing the environment variables?
- Can you invoke `git` from within *AndroidStudio*'s **Terminal**-Window?

**Comment by punkifier** [comment]
I did that, but then it displayed a new error 
![problem3](https://cloud.githubusercontent.com/assets/25942684/23297271/d87e0724-fab3-11e6-9952-480361f4253a.PNG)

**Comment by larsgrefer** [comment]
@punkifier I assume `'git rev-list --count HEAD'.execute(...).text.trim()` retuned an empty string and the error you are seeing is the [message](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getMessage--) of a [NumberFormatException](https://docs.oracle.com/javase/8/docs/api/java/lang/NumberFormatException.html) thrown by [Integer.parseInt(...)](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#parseInt-java.lang.String-)
