### ISSUE TITLE
New phone program will not install

### ISSUE THREAD

**Issue by lionessvudo** [CellularPrivacy/Android-IMSI-Catcher-Detector#915]
### Agreements

- [ ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [ ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [ ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

**Comment by larsgrefer** [comment]
Please update the text of your issue. It just contains the raw issue template.

What exactly is your problem? What steps have you already tried?

**Comment by lionessvudo** [comment]
I signed into github downloaded apk. Zip when I go to open it it will not
open it says can not open file. File explorer or chrome will not open it it
was a while back 2 phones ago I installed program I happen to need the
program . to catch a thief that has stole my other phone this program gives
me the info from phones .. Enough to locate it next door he is my the if
and has been for 7 months..

**Comment by Nordlenning** [comment]
Please close
