### ISSUE TITLE
OpenCellID closing

### ISSUE THREAD

**Issue by Gitschubser** [CellularPrivacy/Android-IMSI-Catcher-Detector#917]
http://wiki.opencellid.org/wiki/Main_Page

https://github.com/mozilla/ichnaea/issues/497

**Comment by takiainen** [comment]
Could you use radiocells.org instead?

**Comment by ShapeShifter499** [comment]
Is this why I haven't been able to download the database?  Does this affect the app's ability to detect a bad cellular base station or sniffer?

**Comment by Nordlenning** [comment]
Hi @ShapeShifter499, see if you're problem is mentioned in or related to issue #854 or #899

**Comment by swampii** [comment]
The app works fine.
And it have worked since SBA-research, stoppede dev.
It anit fals alarms, it is a reality

**Comment by Oroo9CeL** [comment]
It seems the opencellid.org database servers are down. Also manually downloading the database brings up an exception.

**Comment by DuckY1987** [comment]
Lol i just wanted to use your app and i don't have any start base now. Just read the wiki article :-( Does somebody has a Database and can share it with us till some solution is in progress?

**Comment by timisagit** [comment]
Likewise, I hoped to start using this app but have no access to a database to reference. Looking forward to this being resolved!

**Comment by gopi-ar** [comment]
Just a note, OCID isn't closing down. My company Unwired Labs has taken over maintainership of this project and on the immediate roadmap are plans to revive it's dying community and data quality.

We're in the middle of transferring data / code / etc to our servers from Enaikoon's and should publish the roadmap on the wiki shortly after that. In the meantime, we're reachable on hello@opencellid.org

Cheers,
Gopi

**Comment by timisagit** [comment]
Great to hear, do you have a rough time frame that you're working to or is it as and when you're able to fit this into your schedule?

**Comment by ShapeShifter499** [comment]
@gopi-ar Great news!

**Comment by Nordlenning** [comment]
#928
