### ISSUE TITLE
Re: Manually DL of OCID db from Opencellid.org... Where/Which?

### ISSUE THREAD

**Issue by OpR8R** [CellularPrivacy/Android-IMSI-Catcher-Detector#920]
### Agreements

- [xx ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [xx ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [xx ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview
Ok, I've resolved that I will never be able to DL the Opencellid db from the app itself, just not gonna happen. I have similarly resolved to DL the db manually from Opencellid.org and place it into it's corresponding folder in android. In order to educate myself as to what I am seeking exactly I searched these issues and while I did not find my exact question I did find my question inserted into another thread: 

![opencellid db query thread cap](https://cloud.githubusercontent.com/assets/13159413/24582241/04bae7d8-16e0-11e7-858f-f507e387faac.PNG)

So I went looking for the file "opencellid.csv." However, when I navigate to the "database" tab on Opencellid.org I am given any number of choices of .csv files, e.g.:

cell_towers.csv.gz (only 1 of these)
cell_towers_diff-2017032902.csv.gz (lots of these)
measurements_1.csv.gz (lots of these too)
last_measurements.csv.gz (only one of these too, way down at the bottom)

![opencellid db dls cap](https://cloud.githubusercontent.com/assets/13159413/24582255/50bf6866-16e0-11e7-81ef-a3e3525671c7.PNG)

Interestingly, however, I see nothing of the "opencellid.csv" that I seek. Similarly, I can seem to find no evidence of "imported ocid db files" also mentioned in the thread kinda anywhere.

What am I doing wrong and/or where is the file that I seek to be found at Opencellid.org?

Thanks for your time and consideration.

**Comment by Nordlenning** [comment]
Please close
