### ISSUE TITLE
Issue #408 closed so... Request explanation of additional map symbols/avatars/icons

### ISSUE THREAD

**Issue by OpR8R** [CellularPrivacy/Android-IMSI-Catcher-Detector#921]
### Agreements

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [s ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

I read in 408 the discussion regarding the various BTS icons and subsequent legend, what do the other symbols indicate? I get little yellow avatar dudes, sometimes more than one at my location, other times green arrow heads pointing off to directions unknown. None seem to be interactive, can someone shed some light on these and any others that one might encounter? Assume I'm an idiot please. (Pretty close to the mark actually.)

*edit* PS: I also checked the wiki so I think I've exhausted my options prior to posting. Please inform if in error.

Thanks for your time and consideration.

**Comment by Nordlenning** [comment]
Please close
