### ISSUE TITLE
Nordlenning: Require clarification on significance of "Bluecells"

### ISSUE THREAD

**Issue by OpR8R** [CellularPrivacy/Android-IMSI-Catcher-Detector#922]
### Agreements

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

AIMSICD v0.1.43-alpha-normal, build numberT-1939,
Samsung SM-G900V, build number MMB29M.G900VVRU2DPJ2

### Overview

Nordlenning: (or anyone really) In #919 you explain how the "bluecells" we see depicted in the map view are not, in fact, BTS locations but rather the location of the device running the app at the moment of discovery, do I have that right?

I understand that this is an AIMSICD issue/site and I do not mean to contravene the spirit of the endeavor but if I may I'd like to show you guys some caps from another app - Cellmapper - that seems to support my initial suspicion that there's something odd going on here. If nothing else I hope to further my understanding of AIMSICD.

By the way, none of this is an "in your face" kinda thing; I was perfectly content with your bluecell explanation until I ran another app and saw what basically amounts to the exact same conditions at my home that I'm seeing in the AIMSICD app and corroboration from the CM app's wiki/manual (see attached) that what I'm seeing are indeed BTS locations. 
![cellmapper wiki example 1](https://cloud.githubusercontent.com/assets/13159413/24638801/544d76e6-18a0-11e7-809a-437b09209761.PNG)
![cellmapper wiki example 2](https://cloud.githubusercontent.com/assets/13159413/24638802/5e44d428-18a0-11e7-9f66-dc81cd865ed6.PNG)
![cellmapper wiki example 3](https://cloud.githubusercontent.com/assets/13159413/24638806/635ff1fe-18a0-11e7-8dc5-194ecb50590b.PNG)

After reading this over and feeling reasonably certain I understand it I mapped my location with Cellmapper and just like AIMSICD I found this:

![cm app example 1](https://cloud.githubusercontent.com/assets/13159413/24639012/b8f83cd8-18a1-11e7-86da-78ad9a03df79.png)
![cm app example 2](https://cloud.githubusercontent.com/assets/13159413/24639017/be590eb4-18a1-11e7-9af6-230278763d90.png)
![cm app example 3](https://cloud.githubusercontent.com/assets/13159413/24639024/c31101fa-18a1-11e7-8409-0770adf0fb4e.png)
![cm app example 4](https://cloud.githubusercontent.com/assets/13159413/24639025/c88fd322-18a1-11e7-84a1-ff835bc0719b.png)
![cm app example 5](https://cloud.githubusercontent.com/assets/13159413/24639028/cf935cc0-18a1-11e7-95ec-dc582a1c2dfd.png)
![cm app example 6](https://cloud.githubusercontent.com/assets/13159413/24639034/d65b6458-18a1-11e7-94b0-bd6ee0bd82ea.png)

This pattern, concentration, and distribution as well as the coverage pattern seems to mimic what I'm seeing in the AIMSICD app. And just to be sure I'm running both of these apps on 3 different Android devices, all are reporting the same thing. These images are from the above mentioned Samsung phone but it really doesn't seem to matter.

Again, I am slowly but surely gaining on the necessary knowledge to be able to interpret these findings myself but as always any and all help I can get, particularly when it comes to to idiosyncrasies of the AIMSICD app, is deeply appreciated. 

Thanks.

**Comment by Nordlenning** [comment]
Please close
