### ISSUE TITLE
Ok, I get it: Seeking help elsewhere but have been asked to ask developer for app's basic methodology.

### ISSUE THREAD

**Issue by OpR8R** [CellularPrivacy/Android-IMSI-Catcher-Detector#923]
### Agreements

- [ x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview
I'm dealing with a problem and have been asked by the group helping me (Verizon technical support) to ask the developers of the apps I'm employing if they can explain, in fairly lay-terms, (or not: since I'm just passing it along I don't need to necessarily understand it all) how the app determines BTS location and identity, i.e., what facets of the phones hardware/firmware are employed to determine bearing/distance/ID/carrier freqs/etc. This in NO way encumbers the app developers or community, I'm just being asked to "prove" I guess that the app employs a solid design and scheme so it's a "someone explains it to me and I explain it to them" situation. The app's name need not even be mentioned, just "the app." Again, any help appreciated then I'm gone. Thanks.

**Comment by Nordlenning** [comment]
Please close
