### ISSUE TITLE
Nexux 5  with Version 1.43,  API works to upload info but I can't download the database.  The process keeps on timing out.

### ISSUE THREAD

**Issue by ramones1** [CellularPrivacy/Android-IMSI-Catcher-Detector#925]
### Agreements

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

**Comment by gaga9999** [comment]
same here on s4. can upload cell data but no download. on the map i only have cells that i detected. no other cells (worldwide). s4 jfltexx, samsung stock rom, root.

**Comment by gaga9999** [comment]
aimsicd 0.1.43.alpha.normal b t1939

**Comment by CrimsonFork** [comment]
Same on my 5.1.1 / 22

**Comment by Dok-T** [comment]
Same for me , but the application crash while downloading bts maps

**Comment by Hung805213** [comment]
I need help w my privacy phone issue....

**Comment by huyusukesan** [comment]
for me too, when i look the opencellid.csv i have this message in:
```
info,code
BBOX too big - limit to 4,000,000 sq.mts.,5
```
when i download the base directly on opencellid.org, it appeared that the base is ~3Gb  !!!

**Comment by Nordlenning** [comment]
Please close
