### ISSUE TITLE
cve

### ISSUE THREAD

**Issue by ecnuchensen** [CellularPrivacy/Android-IMSI-Catcher-Detector#929]
### Agreements

- [ ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [ ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [ ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

**Comment by nsk** [comment]
yes

**Comment by Jinovas** [comment]
I agree to all if the above

**Comment by nicdroid2** [comment]
I agree to all if the above

**Comment by mimi89999** [comment]
Issue is empty. Closing...
