### ISSUE TITLE
Suggestion:  Setting up a live chat to discuss things.

### ISSUE THREAD

**Issue by ShapeShifter499** [CellularPrivacy/Android-IMSI-Catcher-Detector#930]
I was just starting a to use this application before the issues with OCID.  I'm wondering if it would help any to have a chatroom or irc channel somewhere to discuss and ask questions about AIMSICD. It seems like a slightly better solution then using "GitHub issues" for everything.

**Comment by larsgrefer** [comment]
We have a chat-room on gitter: https://gitter.im/CellularPrivacy/Android-IMSI-Catcher-Detector

**Comment by ShapeShifter499** [comment]
Maybe this could be mentioned somewhere on the README.   Unless I missed it, I don't see it.

**Comment by larsgrefer** [comment]
I've added a badge to the README
