### ISSUE TITLE
at console not working

### ISSUE THREAD

**Issue by treakiandroid** [CellularPrivacy/Android-IMSI-Catcher-Detector#933]
My device runs lineageos with root and i have allowed your app to become root. But the at console is still not available. Could you fix that and also give some gsm at command documentation in the wiki. I only know ATDT number to dail using tone dailing and ++++++++
ATH to hangup from the old modem days. Ok there is also ATI to get modem information. But what are the gsm chip specific AT commands?

Thanks a lot in advance and keep up the good work

**Comment by Nordlenning** [comment]
#754
