### ISSUE TITLE
APKs missing from F-Droid

### ISSUE THREAD

**Issue by grrrrr** [CellularPrivacy/Android-IMSI-Catcher-Detector#936]
### Agreements

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [ x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

AIMSIC no longer seems to be on F-Doid.  Any attempts to download result in 404 errors

**Comment by mimi89999** [comment]
I moved it to the archive since last release was a long time ago and it contained many bugs.

**Comment by grrrrr** [comment]
@mimi89999 were they not offering [v0.1.43-alpha](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/releases), that is what my f-droid app says, which from what I can see is the latest?

**Comment by mimi89999** [comment]
We were offering it, but *v0.1.43-alpha* is from *May 2, 2016*.

**Comment by grrrrr** [comment]
>  but v0.1.43-alpha is from May 2, 2016

@mimi89999 right but am I missing something or is this version any way not the latest fof AIMSICD, should we not be using the version available from Github either?

What version should we be using?
