### ISSUE TITLE
Is the App still working?

### ISSUE THREAD

**Issue by DAMBAE** [CellularPrivacy/Android-IMSI-Catcher-Detector#938]
Hi,

I installed the app today and want to know whether the app is stil working?

I tried to request the OpenCellID but it didn't´t work. I didn't´t get the Code.

Thanks and Regards.

**Comment by beerisgood** [comment]
Short: No.
See https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/926

**Comment by DAMBAE** [comment]
ok, thank you for your fast answer.

2017-08-12 8:22 GMT+02:00 beerisgood <notifications@github.com>:

**Comment by Nordlenning** [comment]
Please close
