### ISSUE TITLE
when does the new app comes out?

### ISSUE THREAD

**Issue by DAMBAE** [CellularPrivacy/Android-IMSI-Catcher-Detector#941]
Hi,

in April 2017 there is an statement from the programmers that the new App (a lite version) comes out soon.

But now we have September. I find the App A-IMSI-Catcher-Detektor better than the SnoopSnitch App.

Programmers , could you please let us know more details about the new date?

Or is the project canceled?

Thank you! Regards

**Comment by larsgrefer** [comment]
You have to ask this question here: https://github.com/5GSD/AIMSICDL
