### ISSUE TITLE
Remove google playservices in AOSP

### ISSUE THREAD

**Issue by pranag30** [CellularPrivacy/Android-IMSI-Catcher-Detector#943]
### Agreements

- [ ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [ ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

**Comment by beerisgood** [comment]
I dont understand your report.
You know this repository is a app and not a rom?
