### ISSUE TITLE
Is the project dead ?

### ISSUE THREAD

**Issue by stemy2** [CellularPrivacy/Android-IMSI-Catcher-Detector#947]
Hello,

The app disappeard from f-droid and aptoide, and there are no release since more than 1 year. Does that means that the pjoect is abandoned ?

Thanks.

**Comment by FFY00** [comment]
Very.

**Comment by stemy2** [comment]
Ok, thanks for your brief and succinct answer.

**Comment by beerisgood** [comment]
See https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/926
